### ISSUE TITLE
Proper Error Message for Custom Error

### ISSUE THREAD

**Issue by prsh9** [uber-go/cadence-client#1013]
When we create a custom error we give a reason and additional details.
Generally custom errors are created to wrap around other errors with additional context/details for e.g.
customErr := cadence.NewCustomError("Error with making HTTP Call", request.URL, err)

The Error() method returns the reason only which can be improved to include the additional details as generally the this method is useful while logging as the reason alone may sometimes be insufficient in the logs.

**Proposed Solution**
Error() can be changed to return `reason + " Details : " + stringify(details)` to give proper message. The `Reason()` and `Details(..)` functions still give us control over the required handling

**Comment by ibarrajo** [comment]
Validated that this is still the case: https://pkg.go.dev/go.uber.org/cadence/internal#NewCustomError 

I believe a reason why the error does not include the stringified details data is that the error message cardinality would increase significantly. This would mean a huge increase on the indexing workload for metrics aggregation when processing the errors.
