### ISSUE TITLE
Add rpc request metrics with retry in consideration

### ISSUE THREAD

**Issue by meiliang86** [uber-go/cadence-client#1015]
**Is your feature request related to a problem? Please describe.**
Right now we have rpc metrics for single requests that does not factor in retry options. Since client does retries automatically, this does not tell the accurate story about the actual failure rate.

**Proposed Solution**
Add metrics after all the retry attempts are exhausted. We can start with sync APIs (start/signal/signalWithStart), and maybe implement this for all if that's not messing up the code too much.

**Comment by anish531213** [comment]
@meiliang86 I didn't understand the purposed solution. As we have backoff retry, these retries should still be counted in the failure rate. Do you mean that we only count this as one failure if there is context timeout?
