### ISSUE TITLE
0.17.0 Thrift Error

### ISSUE THREAD

**Issue by ding1992** [uber-go/cadence-client#1107]
**Describe the bug**
Code compatibility issue with thrift 0.13.0

**To Reproduce**
Is the issue reproducible? 
Yes

**Steps to reproduce the behavior:**
`go get go.uber.org/cadence@v0.17.0`

**Expected behavior**
No error

**Actual behavior**

> ../../../../pkg/mod/go.uber.org/cadence@v0.17.0/internal/common/thrift_util.go:31:38: not enough arguments in call to thrift.NewTSerializer().Write
        have (thrift.TStruct)
        want (context.Context, thrift.TStruct)
../../../../pkg/mod/go.uber.org/cadence@v0.17.0/internal/common/thrift_util.go:47:18: not enough arguments in call to v.Write
        have (thrift.TProtocol)
        want (context.Context, thrift.TProtocol)
../../../../pkg/mod/go.uber.org/cadence@v0.17.0/internal/common/thrift_util.go:53:27: not enough arguments in call to t.Protocol.Flush
        have ()
        want (context.Context)
../../../../pkg/mod/go.uber.org/cadence@v0.17.0/internal/common/thrift_util.go:57:28: not enough arguments in call to t.Transport.Flush
        have ()
        want (context.Context)
../../../../pkg/mod/go.uber.org/cadence@v0.17.0/internal/common/thrift_util.go:67:39: not enough arguments in call to thrift.NewTDeserializer().Read
        have (thrift.TStruct, []byte)
        want (context.Context, thrift.TStruct, []byte)
../../../../pkg/mod/go.uber.org/cadence@v0.17.0/internal/common/thrift_util.go:79:21: not enough arguments in call to ts[i].Read
        have (thrift.TProtocol)
        want (context.Context, thrift.TProtocol)

**Comment by Min-Feng** [comment]
I have the same problem
How do I solve this?

My version
go version go1.16.4 linux/amd64

**Comment by longquanzheng** [comment]
See @Groxx comment https://github.com/uber-go/cadence-client/issues/1129#issuecomment-932554933

**Comment by longquanzheng** [comment]
Make sure you use the right version of thrift 

Thrift 0.9.3 (use [homebrew](https://formulae.brew.sh/formula/thrift@0.9) or [distribution](https://downloads.apache.org/thrift/0.9.3/))

**Comment by longquanzheng** [comment]
You can pin the thrift version: like this: https://github.com/uber/cadence/blob/d3d06825adcf11c20ec3fc58e329f1d9560bb729/go.mod#L92
