### ISSUE TITLE
Update apache thrift version in cadence client library

### ISSUE THREAD

**Issue by swamvenk** [uber-go/cadence-client#1128]
**Describe the bug**
From the [commit id ](https://github.com/apache/thrift/commit/b2a4d4ae21c789b689dd162deb819665567f481c) of apace/thrift dependency I see that we are using v0.10.0 of apace/thrift. But we have [multiple CVEs](https://www.cvedetails.com/vulnerability-list/vendor_id-45/product_id-38295/Apache-Thrift.html) filed that needs updating the library to the latest version (v0.14.x) 

**To Reproduce**
Is the issue reproducible? 
- Yes

**Steps to reproduce the behavior:**
Everyone using cadence client library will get apache/thrift older versions as an implicit dependency and upon checking for security vulnerabilities we get the CVEs flagged

**Expected behavior**
Up-to-date apache/thrift dependency

**Comment by longquanzheng** [comment]
Hi Cadence is moving towards gRPC and it’ll almost there. After migrate to gRPC you can turn off the thrift ports. There will be a period that we will support both protocols until some time that we decided to deprecate thrift. 

Would it solve this problem for you?

**Comment by rafalmnich** [comment]
@longquanzheng I understand the move to gRPC, but you have broken releases, that are not upgradable. And memory leaks in previous versions (hopefully not in the newest - but no way to try). How can you fix that?

**Comment by anitgandhi** [comment]
👋 For what it's worth, we faced this same problem, and this was all we needed to fix it: https://github.com/digitalocean/cadence-client/pull/1/files

We've just been maintaining that fork and carrying that patch forward

**Comment by ibarrajo** [comment]
Closing this since the dependency (github.com/apache/thrift) has been updated:

https://github.com/uber-go/cadence-client/blob/master/go.mod#L6
