### ISSUE TITLE
When can we expect a new release?

### ISSUE THREAD

**Issue by petergardfjall** [uber-go/cadence-client#1254]
There has been over a year since the last tagged release of the client library (`v0.19.1`).
When can a new one be expected?

In order to use the latest released version we need to pin the thrift library in our `go.mod` file like so (see [issue#523](https://github.com/uber-go/cadence-client/issues/523))

```
replace github.com/apache/thrift => github.com/apache/thrift v0.0.0-20190309152529-a9b748bb0e02
```

Relying on a commit would certainly be possible, but it would be nice with a tagged release as an indicator of stability.

**Comment by Groxx** [comment]
Yesterday!  It had been too long, you're right.
