### ISSUE TITLE
The checksum for release version 1.2.9 has changed

### ISSUE THREAD

**Issue by lztetreault-dev** [uber-go/cadence-client#1332]
**Describe the bug**
The checksum for release `1.2.9` has changed since it was initially released. We have a repository that was updated to `1.2.9` on April 2nd, 2024, but now running go mod vendor on that same repo spits out a checksum error as seen in  the screenshots below.

Here is a diff between an instance of the package previously downloaded for `v1.2.9` vs what is downloaded now for the same version

```diff
diff --color -r ./vendor/go.uber.org/cadence/CHANGELOG.md ../<new-go-project>/vendor/go.uber.org/cadence/CHANGELOG.md
8,14d7
< ## [v1.2.9] - 2024-03-01
< ### Added
< - retract directive for v1.2.8
< 
< ### Changed
< - Revert breaking changes from v1.2.8 (#1315)
< 
diff --color -r ./vendor/go.uber.org/cadence/internal/version.go ../<new-go-project>/vendor/go.uber.org/cadence/internal/version.go
46c46
< const LibraryVersion = "1.2.9"
---
> const LibraryVersion = "1.2.8"
```

Old Repo `go.sum`: 
```
go.uber.org/cadence v1.2.9 h1:+jo3lVHy9XSGfmbOLVEh6mSmgHnALcBdoSvIQqSdnOc=
go.uber.org/cadence v1.2.9/go.mod h1:EL7wjwJZVbFvNWkp39NQh9jB1ZLWsu9Gy3Z7Jecx2Z8=
```
New Repo `go.sum`:
```
go.uber.org/cadence v1.2.9 h1:oGERGAnF8RwLMzW2POR2iKKbrcsntkkdNQ1Kuh7tD2w=
go.uber.org/cadence v1.2.9/go.mod h1:EL7wjwJZVbFvNWkp39NQh9jB1ZLWsu9Gy3Z7Jecx2Z8=
```

**To Reproduce**
Is the issue reproducible? 
- Yes 

**Steps to reproduce the behavior:**
-  Check If you have a previous version of the package in your vendored files with the checksum `+jo3lVHy9XSGfmbOLVEh6mSmgHnALcBdoSvIQqSdnOc=`
- Run go mod vendor/tidy and it should fail

**Expected behavior**
The checksum should not have changed on a released version of the package

**Screenshots**
<img width="571" alt="image" src="https://github.com/uber-go/cadence-client/assets/50848874/4c9e38be-dffe-405e-82f1-26e96877f92f">

**Additional context**
Go version: `1.22.2`

**Comment by ibarrajo** [comment]
Thank you for bringing it up, this update should probably been a patch or a minor version bump.
