### ISSUE TITLE
Redesign registration APIs to support custom names

### ISSUE THREAD

**Issue by sivakku** [uber-go/cadence-client#141]
Uberfx has this new DIG framework, this task is if we can use to integrate with that framework. We also need to spend some time to understand what this is going to help us before we integrate.

https://github.com/uber-go/dig

**Comment by madhuravi** [comment]
Based on discussion with team, the redesign included adding support for external aliases for workflows/activities. This is so users running them in different repos have a layer of isolation from the workflow/activity code and less susceptible to code/package/repo changes.

We decided to table the UberFx piece for now until we receive initial customer feedback and once Fx is more stable, we will revisit UberFx/Dig integration.

Code to support external aliases is checked in.
