### ISSUE TITLE
unit test: mock activity sleep on workflow clock

### ISSUE THREAD

**Issue by yiminc** [uber-go/cadence-client#151]
when user mock an activity, we need a way for user to say that the mocked activity would sleep/delay a certain amount of time on workflow clock.
The code would looks something like:
env := testSuite.NewTestWorkflowEnvironment()
env.OnActivity(myActivity, mock.Anything).After(time.Hour).return(mockValues...)

For the above code to work, it needs our PR to testify get merged. If not, then the code would looks like:
waitCh := env.After(time.Hour)
env.OnActivity(myActivity, mock.Anything).WaitUntil(waitCh).return(mockValues...)

**Comment by visaals** [comment]
Is this feature already implemented? I'm trying to find the API on the java cadence client. Thanks.
