### ISSUE TITLE
How to read configuration in the workflow/decider

### ISSUE THREAD

**Issue by sivakku** [uber-go/cadence-client#17]

**Comment by molteanu** [comment]
Does the SideEffect feature not address this? (https://github.com/uber-go/cadence-client/blob/master/workflow.go#L525)

**Comment by sivakku** [comment]
The side effect should help here, this task was filed way before we designed side effect. Either we can close this and open a new one (or) use this to provide a sample of reading configuration.

**Comment by molteanu** [comment]
Closing this.
