### ISSUE TITLE
Add public method to produce stack trace dump of the workflow

### ISSUE THREAD

**Issue by mfateev** [uber-go/cadence-client#173]
Currently there is no clean public method to produce workflow stack trace. Strawman methods signature:

```
Client interface {
    ...
    GetStackTraceDump(workflowID, runID string) (string, error)

    GetStackTraceDumpForHistory(h *s.History) (string, error)
}
```

**Comment by molteanu** [comment]
https://github.com/uber-go/cadence-client/commit/47ca9f74d800223f4fa72b486ae07bf465a8852f
