### ISSUE TITLE
Bug: Reorder history duplicate a event to play twice b/c of slice copy

### ISSUE THREAD

**Issue by sivakku** [uber-go/cadence-client#187]
- We hit a bug in the slice copying that we can overwrite an element in the underlying slice, that can have side affects replaying the item twice.

History to reproduce this bug:

1, 2017-07-21T09:48:42-07:00, WorkflowExecutionStarted: (WorkflowType:(Name:code.uber.internal/devexp/cadence-server/health/driver.stressDriverWorkflow), TaskList:(Name:testTaskList-0), Input:[len=681], ExecutionStartToCloseTimeoutSeconds:2592000, TaskStartToCloseTimeoutSeconds:60)
2, 2017-07-21T09:48:42-07:00, DecisionTaskScheduled: (TaskList:(Name:testTaskList-0), StartToCloseTimeoutSeconds:60)
3, 2017-07-21T09:48:42-07:00, DecisionTaskStarted: (ScheduledEventId:2, Identity:23457@sivakk-C02S608BG8WM@testTaskList-0, RequestId:83535618-c5e6-488c-8ede-f26acb5a64d3)
4, 2017-07-21T09:48:42-07:00, DecisionTaskCompleted: (ExecutionContext:[len=0], ScheduledEventId:2, StartedEventId:3, Identity:23457@sivakk-C02S608BG8WM@testTaskList-0)
5, 2017-07-21T09:48:42-07:00, TimerStarted: (TimerId:0, StartToFireTimeoutSeconds:1, DecisionTaskCompletedEventId:4)
6, 2017-07-21T09:48:42-07:00, StartChildWorkflowExecutionInitiated: (EventId:6, Timestamp:1500655722445724337, EventType:StartChildWorkflowExecutionInitiated, StartChildWorkflowExecutionInitiatedEventAttributes:(Domain:stress-domain, WorkflowId:318f9dd9-75ec-4e08-89a9-33686d0e2e8c_1, WorkflowType:(Name:code.uber.internal/devexp/cadence-server/health/driver.activityWorkflow), TaskList:(Name:testTaskList-0), Input:[len=182], ExecutionStartToCloseTimeoutSeconds:600, TaskStartToCloseTimeoutSeconds:60, ChildPolicy:TERMINATE, Control:[len=0], DecisionTaskCompletedEventId:4))
7, 2017-07-21T09:48:42-07:00, StartChildWorkflowExecutionInitiated: (EventId:7, Timestamp:1500655722445746884, EventType:StartChildWorkflowExecutionInitiated, StartChildWorkflowExecutionInitiatedEventAttributes:(Domain:stress-domain, WorkflowId:318f9dd9-75ec-4e08-89a9-33686d0e2e8c_2, WorkflowType:(Name:code.uber.internal/devexp/cadence-server/health/driver.activityWorkflow), TaskList:(Name:testTaskList-1), Input:[len=184], ExecutionStartToCloseTimeoutSeconds:600, TaskStartToCloseTimeoutSeconds:60, ChildPolicy:TERMINATE, Control:[len=0], DecisionTaskCompletedEventId:4))
8, 2017-07-21T09:48:42-07:00, ChildWorkflowExecutionStarted: (EventId:8, Timestamp:1500655722502841977, EventType:ChildWorkflowExecutionStarted, ChildWorkflowExecutionStartedEventAttributes:(Domain:stress-domain, InitiatedEventId:6, WorkflowExecution:(WorkflowId:318f9dd9-75ec-4e08-89a9-33686d0e2e8c_1, RunId:ef9a9ea9-86d1-408d-924f-3703a9af6512), WorkflowType:(Name:code.uber.internal/devexp/cadence-server/health/driver.activityWorkflow)))
9, 2017-07-21T09:48:42-07:00, DecisionTaskScheduled: (TaskList:(Name:testTaskList-0), StartToCloseTimeoutSeconds:60)
10, 2017-07-21T09:48:42-07:00, ChildWorkflowExecutionStarted: (EventId:10, Timestamp:1500655722601243377, EventType:ChildWorkflowExecutionStarted, ChildWorkflowExecutionStartedEventAttributes:(Domain:stress-domain, InitiatedEventId:7, WorkflowExecution:(WorkflowId:318f9dd9-75ec-4e08-89a9-33686d0e2e8c_2, RunId:7b7283e1-ad4f-4e03-a212-7e17239f9607), WorkflowType:(Name:code.uber.internal/devexp/cadence-server/health/driver.activityWorkflow)))
11, 2017-07-21T09:48:43-07:00, DecisionTaskStarted: (ScheduledEventId:9, Identity:23457@sivakk-C02S608BG8WM@testTaskList-0, RequestId:dae42b63-45a5-498e-923f-4518f948aed5)
12, 2017-07-21T09:48:43-07:00, TimerFired: (TimerId:0, StartedEventId:5)
13, 2017-07-21T09:48:43-07:00, DecisionTaskCompleted: (ExecutionContext:[len=0], ScheduledEventId:9, StartedEventId:11, Identity:23457@sivakk-C02S608BG8WM@testTaskList-0)
14, 2017-07-21T09:48:43-07:00, DecisionTaskScheduled: (TaskList:(Name:testTaskList-0), StartToCloseTimeoutSeconds:60)
15, 2017-07-21T09:48:44-07:00, DecisionTaskStarted: (ScheduledEventId:14, Identity:23457@sivakk-C02S608BG8WM@testTaskList-0, RequestId:55942768-0904-4b47-9407-3afdad1e849a)
16, 2017-07-21T09:48:44-07:00, ChildWorkflowExecutionCompleted: (EventId:16, Timestamp:1500655724921285000, EventType:ChildWorkflowExecutionCompleted, ChildWorkflowExecutionCompletedEventAttributes:(Result_:[len=0], Domain:stress-domain, WorkflowExecution:(WorkflowId:318f9dd9-75ec-4e08-89a9-33686d0e2e8c_2, RunId:7b7283e1-ad4f-4e03-a212-7e17239f9607), WorkflowType:(Name:code.uber.internal/devexp/cadence-server/health/driver.activityWorkflow), InitiatedEventId:7, StartedEventId:10))
17, 2017-07-21T09:48:44-07:00, DecisionTaskCompleted: (ExecutionContext:[len=0], ScheduledEventId:14, StartedEventId:15, Identity:23457@sivakk-C02S608BG8WM@testTaskList-0)
18, 2017-07-21T09:48:44-07:00, TimerStarted: (TimerId:3, StartToFireTimeoutSeconds:1, DecisionTaskCompletedEventId:17)
19, 2017-07-21T09:48:44-07:00, StartChildWorkflowExecutionInitiated: (EventId:19, Timestamp:1500655724956420861, EventType:StartChildWorkflowExecutionInitiated, StartChildWorkflowExecutionInitiatedEventAttributes:(Domain:stress-domain, WorkflowId:318f9dd9-75ec-4e08-89a9-33686d0e2e8c_4, WorkflowType:(Name:code.uber.internal/devexp/cadence-server/health/driver.activityWorkflow), TaskList:(Name:testTaskList-0), Input:[len=182], ExecutionStartToCloseTimeoutSeconds:600, TaskStartToCloseTimeoutSeconds:60, ChildPolicy:TERMINATE, Control:[len=0], DecisionTaskCompletedEventId:17))
20, 2017-07-21T09:48:44-07:00, StartChildWorkflowExecutionInitiated: (EventId:20, Timestamp:1500655724956434333, EventType:StartChildWorkflowExecutionInitiated, StartChildWorkflowExecutionInitiatedEventAttributes:(Domain:stress-domain, WorkflowId:318f9dd9-75ec-4e08-89a9-33686d0e2e8c_5, WorkflowType:(Name:code.uber.internal/devexp/cadence-server/health/driver.activityWorkflow), TaskList:(Name:testTaskList-1), Input:[len=184], ExecutionStartToCloseTimeoutSeconds:600, TaskStartToCloseTimeoutSeconds:60, ChildPolicy:TERMINATE, Control:[len=0], DecisionTaskCompletedEventId:17))
21, 2017-07-21T09:48:44-07:00, DecisionTaskScheduled: (TaskList:(Name:testTaskList-0), StartToCloseTimeoutSeconds:60)
22, 2017-07-21T09:48:45-07:00, ChildWorkflowExecutionStarted: (EventId:22, Timestamp:1500655725106706958, EventType:ChildWorkflowExecutionStarted, ChildWorkflowExecutionStartedEventAttributes:(Domain:stress-domain, InitiatedEventId:19, WorkflowExecution:(WorkflowId:318f9dd9-75ec-4e08-89a9-33686d0e2e8c_4, RunId:57cfbce5-4b2d-4daa-9cc5-8a6053361b6c), WorkflowType:(Name:code.uber.internal/devexp/cadence-server/health/driver.activityWorkflow)))
23, 2017-07-21T09:48:45-07:00, ChildWorkflowExecutionStarted: (EventId:23, Timestamp:1500655725218379514, EventType:ChildWorkflowExecutionStarted, ChildWorkflowExecutionStartedEventAttributes:(Domain:stress-domain, InitiatedEventId:20, WorkflowExecution:(WorkflowId:318f9dd9-75ec-4e08-89a9-33686d0e2e8c_5, RunId:f8f1abae-9d91-4e9e-8b6f-79636ee577d3), WorkflowType:(Name:code.uber.internal/devexp/cadence-server/health/driver.activityWorkflow)))
24, 2017-07-21T09:48:45-07:00, TimerFired: (TimerId:3, StartedEventId:18)
25, 2017-07-21T09:48:47-07:00, DecisionTaskStarted: (ScheduledEventId:21, Identity:23457@sivakk-C02S608BG8WM@testTaskList-0, RequestId:2664c784-a9b7-4252-8f60-09038b41b24b)
26, 2017-07-21T09:49:47-07:00, DecisionTaskTimedOut: (ScheduledEventId:21, StartedEventId:25, TimeoutType:START_TO_CLOSE)
27, 2017-07-21T09:49:47-07:00, DecisionTaskScheduled: (TaskList:(Name:testTaskList-0), StartToCloseTimeoutSeconds:60)

**Comment by venkat1109** [comment]
#188 fixes this bug.
