### ISSUE TITLE
TestFramework: Workflow and activity panics should be handled gracefully

### ISSUE THREAD

**Issue by madhuravi** [uber-go/cadence-client#214]
In the client code path, any panics are wrapped as a PanicError and returned to the caller. In the test environment, we do not have such a wrapper. Panics are propagated up to the test. With activity panics, it is hard to test since the panic happens on a separate goroutine and does not get caught by recover() in a test.

See https://github.com/uber-go/cadence-client/pull/213

**Comment by ryanwalls** [comment]
I'm stuck trying to find where a panic is happening in an activity, and this would be very useful.
