### ISSUE TITLE
Avoid service client and use workflow client in the worker.

### ISSUE THREAD

**Issue by sivakku** [uber-go/cadence-client#216]
From conversation with Venkat this morning:
We have WorkflowClient, DomainClient, Worker, three important classes exposed to user. The Worker takes service client instead of workflow client and the can lead to confusion about what kind of client need to be created depending on whether i am starting workers or starting a workflow. This task is the worker to take WorkflowClient instead of TChannel service client.

**Comment by dmetzgar** [comment]
This seems to no longer be the case.
