### ISSUE TITLE
Incorrect handling of cadence.Now(ctx)

### ISSUE THREAD

**Issue by samarabbas** [uber-go/cadence-client#221]
Client framework seems to have incorrect handling of cadence.Now(), if we capture the result into a variable then it ends up having incorrect value on replay.  Here is the code:
```
for i := 0; i < 10; i++ {
    startTime := cadence.Now(ctx).UnixNano()
    cadence.ExecuteActivity(aCtx, cronActivity, startTime, config, jobName, jobFreq, beginSeq)
    cadence.Sleep(ctx, cronSchedulerFreq)
    elapsed := time.Duration(cadence.Now(ctx).UnixNano() - startTime)
    profile.scope.Timer(timerDriftLatency).Record(absDurationDiff(elapsed, cronSchedulerFreq))
    beginSeq += maxJobsInMinute
  }
```
If the activity takes 55 seconds and 'cronSchedulerFreq' is 59 seconds, the code above ends up computing the drift to be around 55 seconds.  If we look at the history I can clearly see that the timer fired right on time and had no drift.
./cmd/cli/cadence-cli --env prod -domain cadence-canary show -w cron.workflow.sanity -r 36f49cd9-334a-4cc1-bf7e-d5a4d881f873
1, 2017-08-25T23:38:55Z, WorkflowExecutionStarted: (WorkflowType:(Name:code.uber.internal/devexp/cadence-canary/canary.cronWorkflow), TaskList:(Name:canary-task-queue), Input:[len=159], ExecutionStartToCloseTimeoutSeconds:1080, TaskStartToCloseTimeoutSeconds:180)
2, 2017-08-25T23:38:55Z, DecisionTaskScheduled: (TaskList:(Name:canary-task-queue), StartToCloseTimeoutSeconds:180)
3, 2017-08-25T23:38:55Z, DecisionTaskStarted: (ScheduledEventId:2, Identity:103@compute1084-dca1@canary-task-queue, RequestId:1c9aae9a-7585-4213-8a32-8ab3c855c0c1)
4, 2017-08-25T23:38:55Z, DecisionTaskCompleted: (ExecutionContext:[len=0], ScheduledEventId:2, StartedEventId:3, Identity:103@compute1084-dca1@canary-task-queue)
5, 2017-08-25T23:38:55Z, MarkerRecorded: (MarkerName:Version, Details:[len=23], DecisionTaskCompletedEventId:4)
6, 2017-08-25T23:38:55Z, ActivityTaskScheduled: (ActivityId:0, ActivityType:(Name:code.uber.internal/devexp/cadence-canary/canary.cronActivity), TaskList:(Name:canary-task-queue), Input:[len=163], ScheduleToCloseTimeoutSeconds:360, ScheduleToStartTimeoutSeconds:180, StartToCloseTimeoutSeconds:180, HeartbeatTimeoutSeconds:0, DecisionTaskCompletedEventId:4)
7, 2017-08-25T23:38:55Z, TimerStarted: (TimerId:1, StartToFireTimeoutSeconds:59, DecisionTaskCompletedEventId:4)
8, 2017-08-25T23:38:55Z, ActivityTaskStarted: (ScheduledEventId:6, Identity:103@compute1084-dca1@canary-task-queue, RequestId:719b7ffb-e0eb-467a-ba35-421dd54663c6)
9, 2017-08-25T23:39:50Z, ActivityTaskCompleted: (Result_:[len=0], ScheduledEventId:6, StartedEventId:8, Identity:103@compute1084-dca1@canary-task-queue)
10, 2017-08-25T23:39:50Z, DecisionTaskScheduled: (TaskList:(Name:canary-task-queue), StartToCloseTimeoutSeconds:180)
11, 2017-08-25T23:39:50Z, DecisionTaskStarted: (ScheduledEventId:10, Identity:110@compute2953-dca1@canary-task-queue, RequestId:bb986916-29d1-4ed1-8fca-52133ead440f)
12, 2017-08-25T23:39:50Z, DecisionTaskCompleted: (ExecutionContext:[len=0], ScheduledEventId:10, StartedEventId:11, Identity:110@compute2953-dca1@canary-task-queue)
13, 2017-08-25T23:39:54Z, TimerFired: (TimerId:1, StartedEventId:7)
14, 2017-08-25T23:39:54Z, DecisionTaskScheduled: (TaskList:(Name:canary-task-queue), StartToCloseTimeoutSeconds:180)
15, 2017-08-25T23:39:54Z, DecisionTaskStarted: (ScheduledEventId:14, Identity:103@compute1084-dca1@canary-task-queue, RequestId:a674dca3-8398-4e00-a858-88443c1e80d6)
16, 2017-08-25T23:39:54Z, DecisionTaskCompleted: (ExecutionContext:[len=0], ScheduledEventId:14, StartedEventId:15, Identity:103@compute1084-dca1@canary-task-queue)
17, 2017-08-25T23:39:54Z, ActivityTaskScheduled: (ActivityId:2, ActivityType:(Name:code.uber.internal/devexp/cadence-canary/canary.cronActivity), TaskList:(Name:canary-task-queue), Input:[len=163], ScheduleToCloseTimeoutSeconds:360, ScheduleToStartTimeoutSeconds:180, StartToCloseTimeoutSeconds:180, HeartbeatTimeoutSeconds:0, DecisionTaskCompletedEventId:16)
18, 2017-08-25T23:39:54Z, TimerStarted: (TimerId:3, StartToFireTimeoutSeconds:59, DecisionTaskCompletedEventId:16)

**Comment by yiminc** [comment]
this is fixed
