### ISSUE TITLE
simplify rate limiter logic

### ISSUE THREAD

**Issue by yiminc** [uber-go/cadence-client#231]
We have 2 rate limiter, pollerRateLimiter and taskRateLimiter. PollerRateLimiter is to protect our server, taskRateLimiter is to protect activity's down stream service.
We only poll task if there is "free worker". There is one potential issue that after task is polled down, but wait on taskLimiter, the wait time will be count against task timeout timer.

Maybe we could simplify the problem by only having one rate limiter to control how fast we poll the task and as soon as task is ready, we hand it over to worker without having another limiter.

The only problem of one limiter approach is that, if the RPS is set to a low number, but poller count is high, let's say user set maxTaskPerSecond=1, but pollerCount=3, in this configuration, it is possible that we start 3 polls within 3s, but there is no task on server so they just wait, and then all of a sudden, all 3 poll returns, then we have 3 tasks to be started at the same time. 
We can fix this problem by limit the poller count to not exceed the maxTaskPerSecond.

**Comment by dmetzgar** [comment]
@yiminc, can this issue be closed? Looks like there's a check-in for it.
