### ISSUE TITLE
better encoding solution

### ISSUE THREAD

**Issue by yiminc** [uber-go/cadence-client#234]
We are using JSON (as default) to encode data. We need a better way to support encoding so that it is possible to:
1) use different encoding for different activities;
2) optionally compress data when needed; (and even adding encryption)

**Comment by samarabbas** [comment]
There is use case where customer may want to override with custom encoder for scenarios like encryption of PII data.  It would be more natural to override Cadence client encoder/decoder to handle encryption.

**Comment by dmetzgar** [comment]
Encryption and/or overriding encoder moved to #579
