### ISSUE TITLE
README.md example in the section labeled `Worker` does not compile

### ISSUE THREAD

**Issue by richardwilkes** [uber-go/cadence-client#271]
Trying to follow the directions here to experiment with cadence and am unable to get the code in the readme to compile. This was with the current master revision of fbf8546955c8e16c42a11be402309ed6e253b0ce but I've also tried some of the more recent tags and they fail to compile as well. In particular, the function `go.uber.org/cadence/.gen/go/cadence.NewTChanWorkflowServiceClient` does not exist.

Could you update the README.md to reflect the current state of the code?

**Comment by madhuravi** [comment]
Thanks for letting us know. Will send out a PR for this shortly.
