### ISSUE TITLE
Documentation clarification: Workflows and Activities running in different workers?

### ISSUE THREAD

**Issue by ryanwalls** [uber-go/cadence-client#289]
Can workflows and their associated activities be run in different workers?  

My use case is that I have a workflow that coordinates work among many asynchronous activities.  

e.g.  My workflow
```
func Workflow(ctx cadence.Context, simulationID int, runSupportOptimization, runDistortionCompensation bool) error {
	// Run preproc
	ao := cadence.ActivityOptions{
		ScheduleToStartTimeout: 10 * time.Second,
		StartToCloseTimeout:    5 * time.Second,
		ScheduleToCloseTimeout: 10 * time.Second,
	}
	preprocContext := cadence.WithActivityOptions(ctx, ao)

	var runPreprocOutput activities.RunPreprocOutput
	err := cadence.ExecuteActivity(preprocContext, activities.RunPreproc, simulationID).Get(ctx, &runPreprocOutput)
	if err != nil {
		return err
	}

	// Run mechanics solver
	mechanicsSolverContext := cadence.WithActivityOptions(ctx, ao)
	var runMechanicsSolverOutput activities.RunMechanicsSolverOutput
	err = cadence.ExecuteActivity(mechanicsSolverContext, activities.RunMechanicsSolver, simulationID, runPreprocOutput.VoxelFileLocation).
		Get(ctx, &runMechanicsSolverOutput)
	if err != nil {
		return err
	}
	return nil
}
```

My simple activity:
```
func RunPreproc(ctx context.Context, simulationID int) (*RunPreprocOutput, error) {
	logger.Log.Debug("In RunPreproc!")
	return nil, cadence.ErrActivityResultPending
}
```

When this activity runs, will it put an item on a task list that could be polled by some other process?  Do I need to use a different task list name in the ActivityOptions?    

Currently we use SWF and we have deciders polling SWF for decision tasks.  And then we have separate activities polling activity task lists for activity tasks.   Is this paradigm supported by cadence?  Is it better to use a different paradigm?  

For example, instead of having separate activity task pollers, we could just have the activities like `RunPreproc` above call some sort of service that starts the work.  Is this more what is intended with cadence?

**Comment by samarabbas** [comment]
Hi @ryanwalls, Cadence provides very similar semantics to SWF.  Cadence server have separate tasklist for Activity and Deciders.  When you start your worker we automatically start polling for both the tasklist under the cover and dispatch tasks to respective activity and decider implementations.
We also support task routing, where you can schedule a task to specific tasklist by overriding ActivityOptions on the context.

**Comment by mfateev** [comment]
Workflow and activity task lists are in different scopes. So even if they have the same name they are still separate entities in the Cadence service and a worker has to poll for them separately. Internally a worker created through cadence.NewWorker contains both activity and workflow worker and they poll independently on both workflow and activity tasks lists with the configured name. Each of them can be disabled using DisableActivityWorker and DisableWorkflowWorker fields of WorkerOptions passed to NewWorker call.
Also by default the activity options passed to a workflow are initialized with a task list name that is the same as the one used to start the given workflow execution. So your understanding is correct that if you want to route an activity to a different worker pool then you have to override task list name in a forked context object using ActivityOptions.

**Comment by ryanwalls** [comment]
@mfateev Thanks!  That answers my question.  Very nice.  FYI, we are migrating our SWF implementation to cadence over the coming months, so I'm sure I'll have more questions.  Do you guys have a slack channel or would posting issues here be the best way to raise clarifying questions?

Also, should I leave this open until more documentation can be added on this?  Your explanation would be great in a readme somewhere.  I would be happy to contribute to the documentation once I understand the inner workings better.

**Comment by mfateev** [comment]
Let's keep it open until the documentation is updated. 
We are working on getting an official support channel for the project. In the meantime just post your question as issues.
