### ISSUE TITLE
Will using a function to create an activity or workflow function work?

### ISSUE THREAD

**Issue by ryanwalls** [uber-go/cadence-client#292]
Will the machinery of cadence have any issue with creating an activity function and workflow function using a function that returns a function like this?
```
func RunVoxelizationFunc(scheduler task.Scheduler) func(ctx context.Context, simulationID int) (*RunVoxelizationOutput, error) {
	return func(ctx context.Context, simulationID int) (*RunVoxelizationOutput, error) {
		logger.Log.Debug("In RunVoxelization!")
		return nil, cadence.ErrActivityResultPending
	}
}
```

When I register it I do something like this:
```
cadence.RegisterActivity(RunVoxelizationFunc(scheduler))
```

In my workflow I would also create it using a function:
```
func WorkflowFunc(scheduler task.Scheduler) func(ctx cadence.Context, simulationID int, runSupportOptimization, runDistortionCompensation bool) error {
	return func(ctx cadence.Context, simulationID int, runSupportOptimization, runDistortionCompensation bool) error {
		// Run preproc
		ao := cadence.ActivityOptions{
			ScheduleToStartTimeout: 10 * time.Second,
			StartToCloseTimeout:    5 * time.Second,
			ScheduleToCloseTimeout: 10 * time.Second,
		}
		preprocContext := cadence.WithActivityOptions(ctx, ao)

		var runPreprocOutput activities.RunVoxelizationOutput
		return cadence.ExecuteActivity(preprocContext, activities.RunVoxelizationFunc(scheduler), simulationID).Get(ctx, &runPreprocOutput)
	}
}
```

The reason I'm asking is I want to be able to "inject" the `task.Scheduler` interface so I can mock it during unit tests.

**Comment by samarabbas** [comment]
Have you looked at [Unit Test Support](https://github.com/uber-go/cadence-client/blob/master/workflow_testsuite.go) already provided by Cadence GO client?  This allows you to easily write unit test for your workflow logic.  Here is an example:

```
type UnitTestSuite struct {
	suite.Suite
	cadence.WorkflowTestSuite
}

func TestUnitTestSuite(t *testing.T) {
	suite.Run(t, new(UnitTestSuite))
}

func (s *UnitTestSuite) TestWorkflowWithMockActivities() {
	env := s.NewTestWorkflowEnvironment()
	env.OnActivity(RunVoxelizationActivity, mock.Anything).Return(result, nil).Once()

	env.ExecuteWorkflow(Workflow, "input")

	s.True(env.IsWorkflowCompleted())
	s.NoError(env.GetWorkflowError())
	env.AssertExpectations(s.T())
}
```

**Comment by mfateev** [comment]
The supported mechanism to inject external dependencies into activities is by providing root context object through cadence WorkerOptions. Something like:

rootCtx := context.WithValue(context.Background(), schedulerKey, scheduler) 
workerOptions := cadence.WorkerOptions{
    ...
    BackgroundActivityContext: rootCtx,
}
worker := cadence.NewWorker(
		service,
		domain,
		"foo",
		workerOptions)

Then in the activity code:

func RunVoxelizationFunc(ctx context.Context, simulationID int) (*RunVoxelizationOutput, error) {
                scheduler := ctx.Value(schedulerKey).(task.Scheduler)
                logger.Log.Debugf("In RunVoxelization with :%v!", scheduler)            
		return nil, cadence.ErrActivityResultPending
}

**Comment by mfateev** [comment]
The context based mechanism also works fine with the unit testing framework Samar referenced above. Just use 

```
	env := s.NewTestWorkflowEnvironment()
        ...
        workerOptions := cadence.WorkerOptions{
            ...
            BackgroundActivityContext: rootCtx,
        }
        env.SetWorkerOptions(workerOptions)

```
to inject rootCtx to activities under a unit test.

**Comment by ryanwalls** [comment]
@mfateev Thanks!  That makes sense.  @samarabbas Yep, we have been doing TDD while we have been building out our workflows.  Very handy testing library you guys have created!  Much easier than testing old SWF workflows by manually creating events.

**Comment by ryanwalls** [comment]
@mfateev The context mechanism doesn't seem to be working with `TestActivityEnvironment`.  When I try to load values from the context they are all `nil`.

Here's my test:

```
package activities

import (
	"github.com/3dsim/workflow/entity/entityfakes"
	"github.com/stretchr/testify/assert"
	"go.uber.org/cadence/testsuite"
	"go.uber.org/cadence/worker"

	"context"
	"testing"
)

type testContextKey string

func TestCompleteEntity(t *testing.T) {
	// arrange
	s := &testsuite.WorkflowTestSuite{}
	env := s.NewTestActivityEnvironment()

	managerKey := testContextKey("some key")
	fakeManager := &entityfakes.FakeManager{}
	ctx := context.WithValue(context.Background(), managerKey, fakeManager)
	workerOptions := worker.Options{BackgroundActivityContext: ctx}
	env.SetWorkerOptions(workerOptions)
	entityID := 10
	orgID := 10

	// act
	_, err := env.ExecuteActivity(CompleteEntity, managerKey, entityID, orgID)

	// assert
	assert.Nil(t, err, "Expected no error")
}
```

Here's my activity:
```
package activities

import (
	"context"
	"github.com/3dsim/workflow/entity"
	"go.uber.org/cadence/activity"
	"go.uber.org/zap"
)

func init() {
	activity.Register(CompleteEntity)
}

// CompleteEntity marks the entity as complete in it's associated data store
func CompleteEntity(ctx context.Context, managerKey string, entityID, organizationID int) error {
	logger := activity.GetLogger(ctx)
	logger.Debug("In CompleteEntity!")
	manager := ctx.Value(managerKey).(entity.Manager)
	err := manager.Complete(entityID, organizationID)
	if err != nil {
		logger.Error("Error completing part", zap.Error(err), zap.Int("entityID", entityID))
		return err
	}
	return nil
}
```

Any ideas?

**Comment by yiminc** [comment]
@ryanwalls 
There are 2 issues in your code:
1) your activity is expecting 2nd parameter to be of type string, but you passing it a testContextKey in the env.ExecuteActivity() call.
2) the type of the key to store and retrieve from context must be the same, but you store it with testContextKey and retrieve it with string.

To fix this, you just simply change your activity's 2nd parameter's type from string to testContextKey and it should work.

**Comment by ryanwalls** [comment]
@yiminc Thanks!  That fixed it.
