### ISSUE TITLE
Implement worker graceful shutdown that waits for tasks to complete

### ISSUE THREAD

**Issue by mfateev** [uber-go/cadence-client#293]
On shutdown a worker should execute the following sequence:

1. Stop polling for new tasks.
2. Interrupt all outstanding polls.
3. Wait for activities to complete up to specified competions timeout.
4. Change activities context to Done.
5. Wait for activities to cancel for another "cancellation timeout"
6. Exit returning error if some activities haven't completed.

**Comment by yux0** [comment]
PR merged: https://github.com/uber-go/cadence-client/pull/677
