### ISSUE TITLE
Expose all functions of mock.Call in MockCallWrapper

### ISSUE THREAD

**Issue by syllant** [uber-go/cadence-client#294]
Hi,

`MockCallWrapper` wraps `mock.Call`, but only exposes a few functions such as `Times/Once/Twice`.

Could you open all the functions or provide a way to access the inner mock? Functions like `AssertNotCalled/AssertNumberOfCalls` seem super important to me.

Thanks
Sylvain

**Comment by yiminc** [comment]
We embedded mock.Mock in the TestWorkflowEnvironment. So you should be able to access those method via the env object.
like so:
	env := s.NewTestWorkflowEnvironment()
	env.OnActivity(...).Return(...).Once()
	env.ExecuteWorkflow(...)
	env.AssertExpectations(...) // or env.AssertNotCalled(...)

**Comment by syllant** [comment]
I did not meant `TestWorkflowEnvironment` (which indeed "**extends**" `mock.Mock`) but `MockCallWrapper`, that is used for activity/child-workflow mocks and which **wraps** `mock.Mock` with a subset of the methods.

E.g. how can you assert that an activity has never been called? I would expect to use `env.OnActivity(...).AssertNotCalled()`. Same to assert the number of times an activity has been called.

**Comment by yiminc** [comment]
The AssertNotCalled() is defined by mock.Mock, not by mock.Call. 
mock.Call embedded mock.Mock so you can make calls on it but what you called is the method on mock.Mock, which we exposed.

**Comment by syllant** [comment]
Thanks, I see now the confusion :)
