### ISSUE TITLE
Feature request: CLI client for cadence

### ISSUE THREAD

**Issue by ryanwalls** [uber-go/cadence-client#301]
In some of the issues I see on the uber/cadence repo I've noticed a `cadence-cli` being mentioned.  Is that open sourced?  

If not, that would be a really handy tool.

**Comment by samarabbas** [comment]
Yes we do have have a cli internally for cadence, but unfortunately it is not open sourced yet.  We have plans to open source the cli but just haven't found the time yet.  Let's keep this issue open until the cli is open sourced.

**Comment by ryanwalls** [comment]
This has been done.  See https://github.com/uber/cadence/tree/master/tools/cli.

I've also created a docker image of it on docker hub: https://hub.docker.com/r/ryanwalls/cadence/
