### ISSUE TITLE
Client support for RetryPolicy as options

### ISSUE THREAD

**Issue by samarabbas** [uber-go/cadence-client#310]
Considering retry is such a common scenario we should have baked in support on client to support retry for Activity/ChildWorkflow.  Currently consumers try to use off the shelf retry libraries to use within Cadence workflows but they are not going to work due to determinism requirement of workflow code.  Which means it is not allowed to use time.Now but instead to code should use Cadence.Now to make sure it is deterministic.  This requirement means that any retry library should be built using Cadence.Now to make sure it can be used within workflow logic.
One idea is to have Cadence client natively support such a retry library which is exposed as an interceptor using ActivityOptions and ChildWorkflowOptions.  It may be interesting to expose such interceptors as extensions for consumers in case they to extend interceptor chain with custom interceptors of their own.

**Comment by dmetzgar** [comment]
Retries already covered in client: https://cadenceworkflow.io/docs/03_goclient/06_retries
