### ISSUE TITLE
How to use workflow.WithValue ?

### ISSUE THREAD

**Issue by h7kanna** [uber-go/cadence-client#318]
Hi,
Docs say it can be used for request-scoped data that transits processes and APIs.
But I do not understand how it can be done? Please point to any usage sample.
Also can we get the Value in a ChildWorkflow?

Thanks,
Harsha

**Comment by mfateev** [comment]
Currently the scope of the value is a single context (or any child that is spawned from it). There is not automatic propagation to activities or child workflows. We are considering adding such feature mostly for Jaeger (https://github.com/jaegertracing/jaeger) context propagation. 
Here is the issue that tracks that: https://github.com/uber/cadence/issues/354

**Comment by h7kanna** [comment]
Thanks @mfateev
