### ISSUE TITLE
Ability to fail workflow on non-deterministic error

### ISSUE THREAD

**Issue by samarabbas** [uber-go/cadence-client#333]
Currently we have some validation on the client to detect when workflow implementation is modified in non-deterministic manner.  Client behavior is to through a panic in the decider which should cause decision to fail with non-deterministic error.  The workflow stays stuck in this state until the workflow implementation is fixed.  
Customers are asking for capability to have an option to fail such workflow executions immediately rather than stuck in this loop.  This is useful for executions which are short lived and it is ok to fail them incase of non-deterministic errors.

**Comment by syllant** [comment]
Yes, seems to me that panicing the process in this case is rather harsh, I think it would be fair to consider that it is not more critical than a regular workflow error; then it's up to developers to decide what they should do in this case.

**Comment by samarabbas** [comment]
Panic'ing the worker process was client bug which is already addressed.  The behavior now is any decider panic is handled by the worker and results in decisiontaskfailed event for that workflow execution.  This helps in debugging such issues as you can get the panic error by looking at workflow execution history.

**Comment by ryanwalls** [comment]
@samarabbas Just checking on the status of the original request.  Is it possible to fail the workflow in this case?

**Comment by mfateev** [comment]
It is possible, but not implemented yet.

**Comment by arthurguber** [comment]
Hi all, 

I've assigned this to myself and will fix. Thanks!

**Comment by yiminc** [comment]
Some people want to restart on non-deterministic error: https://github.com/uber-go/cadence-client/issues/368
