### ISSUE TITLE
Create tests for Signal External Workflow

### ISSUE THREAD

**Issue by vancexu** [uber-go/cadence-client#347]
Currently there is no easy way to test two running workflow interaction in the workflow tests. Need to add these for SignalExternalWorkflow, CancelExternalWorkflow etc.

**Comment by ethernetdan** [comment]
Any updates or workarounds in this area?

**Comment by vancexu** [comment]
> Any updates or workarounds in this area?

This issue is majorly for cadence internal test cases, and shouldn't affect cadence user tests.
For user to test signalExternalWorkflow, use mock like `OnSignalExternalWorkflow` from testsuite should be enough right?
