### ISSUE TITLE
Mockery unable to generate client for client.Client

### ISSUE THREAD

**Issue by samarabbas** [uber-go/cadence-client#359]
After moving to GO type aliases we noticed mockery is unable to generate valid mocks for client.Client interface.  This is going to be an issue for cadence customers to write unit test for code which involves starting workflow executions.

**Comment by yiminc** [comment]
this is a tooling issue, file issues for mockery and gomock
https://github.com/vektra/mockery/issues/181
https://github.com/golang/mock/issues/144

**Comment by yiminc** [comment]
we have added generated mock files to the SDK.
