### ISSUE TITLE
ExecuteLocalActivity panics if nil is passed as argument to activity

### ISSUE THREAD

**Issue by ryanwalls** [uber-go/cadence-client#360]
Took me a while to track down what was happening.  https://github.com/uber-go/cadence-client/blob/master/internal/internal_activity.go#L176 panics if nil is an argument to an activity.  If nil is not allowed, it should ideally print a more user friendly message.  If nil is allowed, should do some safer type checking at https://github.com/uber-go/cadence-client/blob/master/internal/internal_activity.go#L204.

**Comment by yiminc** [comment]
This happen to regular activity as well.
I think we need to fix this to allow nil passed in as argument to activity.
I will send a fix soon.
