### ISSUE TITLE
Support automatic restart of a workflow on non deterministic error.

### ISSUE THREAD

**Issue by mfateev** [uber-go/cadence-client#368]
Some workflows (like cronjobs) can be restarted from the beginning on every code change. For them using GetVersion feature is overkill. The proposed solution is to call ContinueAsNew with original arguments every time a non deterministic change of the code is detected. This way the an updated code can be safely deployed.

**Comment by dmetzgar** [comment]
This just needs documentation.

**Comment by longquanzheng** [comment]
https://github.com/uber/cadence/pull/2007
