### ISSUE TITLE
Documentation request: How to handle workflow timeouts

### ISSUE THREAD

**Issue by ryanwalls** [uber-go/cadence-client#374]
I have some cleanup that I need to do when a workflow times out.  Running the cleanup when an activity times out is straightforward.  How do you listen for workflow level timeouts?

The only obvious thing to me is to run my workflow as a child workflow.  Then in the parent workflow I do the cleanup if the child returns an error.  Is there a better way?

**Comment by mfateev** [comment]
IMHO workflow timeout (unless it is a child workflow) is just to ensure that you don't have runaway instances. All other timeout logic should be par of the workflow definition. 
Here is one way to do it:

```
func MyWorkflowWithTimeout(ctx workflow.Context) error {
	ctx1, cancelF := workflow.WithCancel(ctx)
	workflow.Go(ctx, func(ctx workflow.Context) {
		workflow.Sleep(ctx, MY_TIMEOUT)
		cancelF()
	})
	return MyWorklfow(ctx1)
}
```
We haven't implemented WithDeadline for the workflow context. After it is implemented the code will look like:

```
func MyWorkflowWithTimeout(ctx workflow.Context) error {
	return MyWorklfow(workflow.WithDeadline(ctx, MY_TIMEOUT))
}

```
I'm keeping this task open until WithDeadline is implemented.

**Comment by samarabbas** [comment]
Another potential option is to use the synchronous ExecuteWorkflow API provided on the client:
https://github.com/uber-go/cadence-client/blob/master/client/client.go#L96

This allows you to wait for workflow completion, which you can use for running cleanup code when  workflow times out.

**Comment by ibarrajo** [comment]
https://cadenceworkflow.io/docs/concepts/activities/#timeouts

https://stackoverflow.com/questions/65139178/how-to-set-proper-timeout-values-for-cadence-activitieslocal-and-regular-activi/65139179#65139179
