### ISSUE TITLE
Feature request: Be able to set start and complete listeners for activities in production code

### ISSUE THREAD

**Issue by ryanwalls** [uber-go/cadence-client#375]
In tests you can use `SetOnActivityCompletedListener` and `SetOnActivityStartedListener`.  Seems like it would be nice to be able to use that paradigm in production code as well.  I have generic start/cleanup logic that needs to happen on every activity in a workflow.  Would be nice to register it once instead of calling it before/after every activity.

**Comment by mfateev** [comment]
You can define your own Register function that wraps activity in your own interceptor and calls activity.Register with your interceptor.

**Comment by ryanwalls** [comment]
@mfateev Good idea.  Still might be nice to be part of the documented framework.  I'll give it a shot.  If I find a way to write it generic enough, perhaps it will be worth submitting a PR.

**Comment by ryanwalls** [comment]
@mfateev I'm having trouble visualizing how this would work.  Seems like I would have to call `ExecuteActivity` using an activity name instead of a function.  

Perhaps something like this?
```
func RegisterWithInterceptor(af interface{}, options activity.RegisterOptions) {
    wrappedAF := wrapWithInterceptor(af)
    activity.RegisterWithOptions(wrappedAF, options)
}
```

Then when I call it in a workflow, I'd have to use the name I registered with, not the function.  
e.g. 
```
func init() {
     RegisterWithInterceptor(myAF, activity.RegisterOptions{Name: "myActivity"})
}

func Workflow(ctx workflow.Context) {
   <skipping setup>
   workflow.ExecuteActivity(myCtx, "myActivity")
}
```

Is this similar to what you were thinking?

**Comment by mfateev** [comment]
You could do something like:

```
func RegisterWithInterceptor(af interface{}) {
    afName := getFunctionName(af)
    wrappedAF := wrapWithInterceptor(af)
    activity.RegisterWithOptions(wrappedAF, &activity.RegisterOptions{Name:afName})
}
```
The problem is that the getFunctionName is not currently public. But I think making it public is reasonable. As a temporary workaround you can just copy its [code](https://sourcegraph.com/github.com/uber-go/cadence-client/-/blob/internal/internal_worker.go#L1105). 

```
func getFunctionName(i interface{}) string {
	return runtime.FuncForPC(reflect.ValueOf(i).Pointer()).Name()
}

```

**Comment by ryanwalls** [comment]
Thanks!  Yeah, this should work.  Feel free to leave this open if you think having the ability to register listeners is something you want eventually.  Otherwise, go ahead and close.

**Comment by ryanwalls** [comment]
@mfateev The interceptor func that I register would have to have the same signature as the activity func right?

**Comment by mfateev** [comment]
Yes. You could use [reflect.MakeFunc](https://golang.org/pkg/reflect/#MakeFunc) to create the wrapper.
It certainly looks like non trivial exercise  at this point. We are going to think how to provide more generic solution to it.

**Comment by mfateev** [comment]
Java supports [WorkflowInterceptor](https://github.com/uber/cadence-java-client/blob/7912a840aefdd3f1ebdb96f94d709f874b95bc44/src/main/java/com/uber/cadence/worker/WorkerOptions.java#L174). I think go should use the same approach. Both Java and Go have to add ActivityInterceptor as well.
