### ISSUE TITLE
Logging Improvement: EntityNotExistError on Activity completion should not be error level

### ISSUE THREAD

**Issue by samarabbas** [uber-go/cadence-client#378]
Currently we log EntityNotExistError on activity completion as log level 'Error'.  It should instead be log level 'Info' as it is expected when workflow execution completed.

cadence_1    | time="2018-01-29T21:24:07Z" level=error msg="RespondActivityTaskCompleted. Error: EntityNotExistsError({Message:Activity task not found.})" RunID=084cbc76-1db4-4eb5-a05b-de6731f5e9b6 ScheduleID=11 Service=cadence-frontend WorkflowID=f3d2eb19-e739-4549-91bd-f779b85037c0

**Comment by yiminc** [comment]
Move to server side issue.

**Comment by wxing1292** [comment]
move back to client since this should be client specific
