### ISSUE TITLE
yarpc.NewDispatcher opens an inbound port

### ISSUE THREAD

**Issue by tsublette** [uber-go/cadence-client#393]
Upon creating a new dispatcher, the process tries to open an inbound port and causes a firewall warning on windows. Why is it opening this port and is there a way to keep it from happening?

```
	b.dispatcher = yarpc.NewDispatcher(yarpc.Config{
		Name: _cadenceClientName,
		Outbounds: yarpc.Outbounds{
			_cadenceFrontendService: {Unary: ch.NewSingleOutbound(b.hostPort)},
		},
	})
```

**Comment by madhuravi** [comment]
This is a bug in YARPC. See https://github.com/yarpc/yarpc-go/issues/1401

**Comment by ryanwalls** [comment]
@mfateev @madhuravi Haven't dug into this much, but is there another transport we could use when we configure the client that wouldn't use yarpc?  When yarpc opens up an inbound port, does it listen on 127.0.0.1 or on 0.0.0.0?

**Comment by ryanwalls** [comment]
Found a potential solution: https://github.com/yarpc/yarpc-go/issues/1401#issuecomment-364785142

Trying it now.

**Comment by madhuravi** [comment]
Sounds good, let us know.

**Comment by vancexu** [comment]
This can be fixed by using,
```
        ch, err := tchannel.NewChannelTransport(
		tchannel.ServiceName(serviceName), tchannel.ListenAddr("127.0.0.1:0"))
	if err != nil {
		logger.Fatal("Failed to create transport channel", zap.Error(err))
	}

	dispatcher = yarpc.NewDispatcher(yarpc.Config{
		Name: clientName,
		Outbounds: yarpc.Outbounds{
			serviceName: {Unary: ch.NewSingleOutbound(hostPort)},
		},
	})
```
