### ISSUE TITLE
Feature request: Document best practice for cancellation

### ISSUE THREAD

**Issue by ryanwalls** [uber-go/cadence-client#402]
We need to execute some "cleanup" steps when a workflow is cancelled.  But on cancellation, if we try to run another activity for the cleanup step, it fails saying the workflow is already cancelled.  

e.g. 
```
        err := workflow.ExecuteActivity(ctx, activities.RunMechanicsSolver).
		Get(ctx, &runMechanicsSolverOutput)
	if err != nil && cadence.IsCanceledError(err) {
		workflow.ExecuteActivity(ctx, activities.HandleCancellation) // This fails because the workflow is already cancelled at this point
		return err
	}
```

What's the best pattern for handling cleanup after cancellation?  I have to call some other API to do the cleanup, so I figured I'd execute it as an activity to make the workflow function deterministic.  Perhaps using a local activity would avoid this problem?  Should I just call the cleanup API directly in the workflow function?

Thanks!

**Comment by mfateev** [comment]
The best pattern is to allow creation of context that is not linked to a parent. The relevant issue is https://github.com/uber-go/cadence-client/issues/140. Let us bump up its priority to get you unblocked. After it is implemented your code will look something like:

```
        err := workflow.ExecuteActivity(ctx, activities.RunMechanicsSolver).
		Get(ctx, &runMechanicsSolverOutput)
	if err != nil && cadence.IsCanceledError(err) {
                // newDisconnectedContext creates context that is not inheriting cancellation
                // from its parent.
                dCtx := workflow.newDisconnectedContext(ctx);
		workflow.ExecuteActivity(dCtx, activities.HandleCancellation)
		return err
	}
```

**Comment by ryanwalls** [comment]
@mfateev Thanks!  Exactly what I would need.  I'll watch the other issue.

**Comment by mfateev** [comment]
Resolved by https://github.com/uber-go/cadence-client/pull/404
