### ISSUE TITLE
Respond with partial set of decisions

### ISSUE THREAD

**Issue by samarabbas** [uber-go/cadence-client#408]
When executing local activities we wait for all activities to complete before responding back with the next set of decisions.  But sometimes it is useful to respond back with partial decisions at some heartbeat interval and still keep the decision open on server.  This reduces the latency for state transitions when some local activities complete much earlier than the rest.
This may require a server change on RespondDecisionTaskCompleted API for completing the decision and keeping it open for more decisions.

**Comment by yiminc** [comment]
This is done here: https://github.com/uber-go/cadence-client/pull/498
