### ISSUE TITLE
Cadence should dump all known activity types if receive a task with unknown activity type.

### ISSUE THREAD

**Issue by wxing1292** [uber-go/cadence-client#418]
Cadence should dump all known activity types if receive a task with unknown activity type.
This can help customer who accidentally change the activity function name.

Similar functionality is already implemented on the workflow side

**Comment by mfateev** [comment]
It would also nice to be able to query for them:

https://github.com/uber/cadence/issues/390

**Comment by arthurguber** [comment]
Hi Wenquan and Max,

By ActivityType, did you mean the name of the activity or something different?
