### ISSUE TITLE
Support for maximum number of inflight workflow executions

### ISSUE THREAD

**Issue by samarabbas** [uber-go/cadence-client#421]
Cadence client can provide support for steadily make progress on workflows in order when large number of such workflows are started.  
The scenario is to start 1 million workflows and have max number of active workflows (like 1000) per worker.  This means a worker picks up decision task for 1000 workflows and stops polling on the global worker tasklist until it has space for more after completion of any of the 1000 sticky workflows.
This would give the semantics of processing workflows in order to churn through the backlog of such large number of workflows.

**Comment by dmetzgar** [comment]
@yycptt is this part of your current work with sessions?

**Comment by yycptt** [comment]
No, I don't think so. I can limit the number of current sessions, but that's on session level, not workflow level.
