### ISSUE TITLE
no way to read heartbeat details from DescribeWorkflowExecution

### ISSUE THREAD

**Issue by yiminc** [uber-go/cadence-client#423]
if pending activity has heartbeat, the result from DescribeWorkflowExecution will include that heartbeat as blob. There is no way to decode that blob into actual object type.

**Comment by vancexu** [comment]
`client.NewValue()` and `NewValues()` can be used to read this.

 NewValue creates a new encoded.Value which can be used to decode binary data returned by Cadence.  For example:
 User had Activity.RecordHeartbeat(ctx, "my-heartbeat") and then got response from calling Client.DescribeWorkflowExecution.
 The response contains binary field PendingActivityInfo.HeartbeatDetails,
 which can be decoded by using:
   var result string // This need to be same type as the one passed to RecordHeartbeat
   NewValue(data).Get(&result)
