### ISSUE TITLE
[feature / cleanup / help-wanted]Parallelize tests to catch more race conditions

### ISSUE THREAD

**Issue by Groxx** [uber-go/cadence-client#432]
At the moment, the vast majority of these tests are run serially, with the `-race` flag.

Unfortunately, since the test runner synchronizes state between each test that's run, the only kinds of data-races that `-race` can detect are internal-to-a-single-test races, which requires that a test run multiple goroutines _and_ trigger the race condition.
That catches some things, and I'm thrilled to see the `-race` flag on there by default, but there are a ton of gaps that are possible.

To test more thoroughly, tests should generally be run in parallel.  Sometimes this'll make them run faster too, but that's not really my goal here.

As a concrete example, I'm working on a pull request which parallelizes a bunch, and it found a race condition where `getRegisteredActivities` doesn't acquire the lock protecting the `activityFuncMap`:
https://github.com/Groxx/cadence-client/commit/3da36d16f92d596f9885548fcb91eb0ccb438c0e#diff-dd4127da46647fa38a69883b7dfe4f1b
From a brief skim, it seems unlikely that this is actually a problem in any reasonable use of Cadence, but it's still not _good_.  And it's a perfect example of why tests should be parallelized by default.

---

At the moment, that branch will eventually fail with nondeterministic workflow errors if you rerun them enough, which I have not yet investigated:
```
2018-04-03T17:03:17.663-0700	ERROR	internal/internal_task_handlers.go:664	Replay and history mismatch.	{"error": "nondeterministic workflow: missing replay decision for ActivityTaskScheduled: (ActivityId:0, Input:[])"}
go.uber.org/cadence/vendor/go.uber.org/zap.Stack
	/Users/stevenl/gopath/src/go.uber.org/cadence/vendor/go.uber.org/zap/field.go:209
go.uber.org/cadence/vendor/go.uber.org/zap.(*Logger).check
	/Users/stevenl/gopath/src/go.uber.org/cadence/vendor/go.uber.org/zap/logger.go:273
go.uber.org/cadence/vendor/go.uber.org/zap.(*Logger).Error
	/Users/stevenl/gopath/src/go.uber.org/cadence/vendor/go.uber.org/zap/logger.go:176
go.uber.org/cadence/internal.(*workflowTaskHandlerImpl).ProcessWorkflowTask
	/Users/stevenl/gopath/src/go.uber.org/cadence/internal/internal_task_handlers.go:664
go.uber.org/cadence/internal.(*TaskHandlersTestSuite).TestWorkflowTask_PressurePoints
	/Users/stevenl/gopath/src/go.uber.org/cadence/internal/internal_task_handlers_test.go:429
runtime.call32
	/usr/local/Cellar/go/1.10.1/libexec/src/runtime/asm_amd64.s:573
reflect.Value.call
	/usr/local/Cellar/go/1.10.1/libexec/src/reflect/value.go:447
reflect.Value.Call
	/usr/local/Cellar/go/1.10.1/libexec/src/reflect/value.go:308
go.uber.org/cadence/vendor/github.com/stretchr/testify/suite.Run.func2
	/Users/stevenl/gopath/src/go.uber.org/cadence/vendor/github.com/stretchr/testify/suite/suite.go:102
testing.tRunner
	/usr/local/Cellar/go/1.10.1/libexec/src/testing/testing.go:777
```
It could be a sign I'm just parallelizing the wrong things.  But I'm hoping to flush out these kinds of potential-problems and either get them fixed or whitelisted, since the current test suite basically ignores them by accident.

Test-runs that trigger that error also reveal another thing that'd be good to fix, but can be addressed separately: none of these inject a per-test-logger that uses `testing.T.Log(f)`, so the output from *all* tests (well, per suite) gets blended together, making it hard to diagnose problems.

---

All of which stuff like `testify.Suite` broadly exacerbates, since it doesn't fit particularly well with how go tests run, now that we have `testing.T.Run` to run sub-tests.  It's hard to parallelize, hard to sub-log, hard to everything, and its _full_ feature-set can be summed up as:
```
func TestSuite(t){
  // setup
  t.Run("sub tests", func(t){
    // sub test setup
  })
  // teardown
}
```
so I try to rip it out whenever possible.

**Comment by arthurguber** [comment]
Due to the fact that this task will take 1 engineer sprint, cadence team decided not to fund this.

However, Cadence team is committed to fixing all bugs uncovered as part of this effort.
