### ISSUE TITLE
Queueing workflows

### ISSUE THREAD

**Issue by alexDrinkwater** [uber-go/cadence-client#459]
Hey Guys, I am trying to come up with a way to use the client methods to implement queueing in cadence. I want to limit the amount of workflows a user can have running and then as workflows complete they somehow signal to complete a wait activity of the oldest workflow that is pending/blocked.

```
func Workflow(ctx workflow.Context, userID string) error {

       // CanStart checks running limit for user and returns activity.ErrResultPending if user is over capacity
       err:= workflow.ExecuteActivity(canStartCtx, CanStart, organizationID, managerKey).Get(canStartCtx, &canStart)
	if err != nil {
		return err
	}

       err = workflow.ExecuteActivity(doStuffCtx, DoStuff).Get(canStartCtx, &canStart)
	if err != nil {
		return err
	}

        // DequeueNextWorkflow needs to find the userIDs pending activities and complete them
	err = workflow.ExecuteLocalActivity(DequeueNextWorkflowCtx, DequeueNextWorkflow, userID).Get(DequeueNextWorkflowCtx, nil)
	if err != nil {
		return err
	}
}
```

Inside DequeueNextWorkflow I call the function below:

```
func (m *manager) CompleteNextPendingActivity(userID int) error {
	archived := false
	simulations, err := m.simulationClient.Simulations(int32(userID), []string{models.SimulationStatusRequested}, []string{"requestedAt:asc"}, 0, 100, &archived)
	if err != nil {
		logger.Log.Error("Failed to get queued simulations", "userID", userID)
		return err
	}

	if len(simulations) == 0 {
		logger.Log.Info("No simulations in requested state", "userID", userID)
		return nil
	}

	workflowExecution, err := m.cadenceClient.DescribeWorkflowExecution(context.Background(), simulations[0].WorkflowID, "")
	if err != nil {
		return err
	}

	pendingActivities := workflowExecution.PendingActivities

	if len(pendingActivities) == 0 {
		logger.Log.Info("No pending activities to complete", "organizationID", organizationID)
		return nil
	}
	runID := *workflowExecution.WorkflowExecutionInfo.Execution.RunId
	logger.Log.Info("Completing activity", "DomainName", m.domainName, "workflowID", simulations[0].WorkflowID, "runID", runID, "activityID", *pendingActivities[0].ActivityID)
	// Assumes only one pending activity
	return m.cadenceClient.CompleteActivityByID(context.Background(), m.domainName, simulations[0].WorkflowID, runID, *pendingActivities[0].ActivityID, true, nil)
}
```

The problem I am having with this approach is that to look up the pending activities using the DescribeWorkflowExecution function I need the runID, however I do not store the runID anywhere at the moment. Is there an easier way to find pendingActivities for a workflowID and complete them? Can I use a cadence query to find them?

**Comment by mfateev** [comment]
I would personally implement it as a separate _Semaphore Workflow_. A job workflow would send a signal to a semaphore workflow and then it would reply with a signal to indicate that permission is granted. This way you completely eliminate the need to call describeWorkflowExecution API as the semaphore workflow can keep the list of pending workflows in its local state.

**Comment by mfateev** [comment]
Another simple option is to not dequeue an activity task until there is a resource to process it. But it assumes that the simulation client would poll for activity task only when it has a spare capacity available.

**Comment by ryanwalls** [comment]
@mfateev We are working on implementing this and have a question about what happens when you are receiving on a signal channel when a cancel is requested.

e.g.
```
queueChannel := workflow.GetSignalChannel(ctx, simulation.DequeuedSignalName)
queueChannel.Receive(ctx, nil)
```

What happens to `Receive` when the context is cancelled?  When executing an activity it returns a `CancelledError` that we can check the type of.  With `Receive` is the channel closed when the context is cancelled?

**Comment by mfateev** [comment]
The cancellation is done by closing a channel returned from ctx.Done() method. queueChannel.Receive returns CancelledError because the context passed to it is cancelled.
If you want to call any operation after a workflow cancellation use a disconnected context when calling it. See https://github.com/uber-go/cadence-client/blob/master/workflow/context.go#L75

**Comment by ryanwalls** [comment]
@mfateev How does `Receive` return a `CancelledError`?  It's signature only has a bool return value?  https://github.com/uber-go/cadence-client/blob/master/internal/workflow.go#L53

**Comment by ryanwalls** [comment]
Do we need to use the SignalChannel interface?  Does getting the encoded value return the `CancelledError`?  https://github.com/uber-go/cadence-client/blob/master/internal/workflow.go#L79

**Comment by ryanwalls** [comment]
All, thanks for your help.  We have figured out a way to do it.  For listening for cancellation while we wait for a signal we will just do a select like outlined here: https://github.com/uber-go/cadence-client/blob/master/internal/context.go#L56-L67

For the queuing we will use a separate semaphore workflow as @mfateev suggested.

**Comment by mfateev** [comment]
Awesome! We are working on improving our external documentation as well as samples to require less digging through the code.
