### ISSUE TITLE
getErrorDetails panic on interface conversion 

### ISSUE THREAD

**Issue by yiminc** [uber-go/cadence-client#511]
Got below error. Repro steps: return custom error from child workflow.

{"level":"error","ts":"2018-06-22T18:30:13.181-0700","caller":"internal/internal_worker_base.go:276","message":"Unhandled panic.","Domain":"samples-domain","TaskList":"helloWorldGroup","WorkerID":"28036@yiminc-C02SH5CBG8WP@helloWorldGroup","WorkerType":"DecisionWorker","PanicError":"interface conversion: encoded.Values is *internal.EncodedValues, not internal.ErrorDetailsValues","PanicStack":"base worker for DecisionWorker [panic]:
code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal.getErrorDetails(0x1b6d1e0, 0xc4203faca0, 0x1b71a20, 0x2130178, 0xc420414640, 0xc42075b608, 0x17c335c, 0x0, 0x0)
\t/Users/yiminc/gocode/src/code.uber.internal/devexp/cadence-samples.git/.tmp/.goroot/src/code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal/internal_utils.go:150 +0x62c
code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal.(*workflowTaskHandlerImpl).completeWorkflow(0xc420442200, 0xc42043f900, 0xc4207d22a0, 0xc4202ba580, 0x0, 0x0, 0x0, 0xc420077b00, 0xc420077938, 0x17cbd8b)
\t/Users/yiminc/gocode/src/code.uber.internal/devexp/cadence-samples.git/.tmp/.goroot/src/code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal/internal_task_handlers.go:1120 +0x636
code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal.(*workflowExecutionContextImpl).CompleteDecisionTask(0xc4202ba580, 0xc4207be701, 0x100, 0x0)
\t/Users/yiminc/gocode/src/code.uber.internal/devexp/cadence-samples.git/.tmp/.goroot/src/code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal/internal_task_handlers.go:752 +0x1f9
code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal.(*workflowExecutionContextImpl).ProcessWorkflowTask(0xc4202ba580, 0xc4207d22a0, 0x1b767a0, 0xc4206da8a0, 0xc4202ba580, 0x0, 0x0, 0x0)
\t/Users/yiminc/gocode/src/code.uber.internal/devexp/cadence-samples.git/.tmp/.goroot/src/code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal/internal_task_handlers.go:719 +0x461
code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal.(*workflowTaskHandlerImpl).ProcessWorkflowTask(0xc420442200, 0xc4207d22a0, 0x1b767a0, 0xc4206da8a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
\t/Users/yiminc/gocode/src/code.uber.internal/devexp/cadence-samples.git/.tmp/.goroot/src/code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal/internal_task_handlers.go:623 +0x226
code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal.(*workflowTaskPoller).processWorkflowTask(0xc4204554a0, 0xc4203ec260, 0x0, 0x0)
\t/Users/yiminc/gocode/src/code.uber.internal/devexp/cadence-samples.git/.tmp/.goroot/src/code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal/internal_task_pollers.go:231 +0xaf
code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal.(*workflowTaskPoller).ProcessTask(0xc4204554a0, 0x1889840, 0xc4203ec260, 0x17ec101, 0xc4200c5540)
\t/Users/yiminc/gocode/src/code.uber.internal/devexp/cadence-samples.git/.tmp/.goroot/src/code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal/internal_task_pollers.go:211 +0xa8
code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal.(*baseWorker).processTask(0xc4200bf520, 0x1889840, 0xc4203ec260)
\t/Users/yiminc/gocode/src/code.uber.internal/devexp/cadence-samples.git/.tmp/.goroot/src/code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal/internal_worker_base.go:285 +0xd7
created by code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal.(*baseWorker).runTaskDispatcher
\t/Users/yiminc/gocode/src/code.uber.internal/devexp/cadence-samples.git/.tmp/.goroot/src/code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal/internal_worker_base.go:236 +0xd9","stack":"code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal.(*baseWorker).processTask.func1
\t/Users/yiminc/gocode/src/code.uber.internal/devexp/cadence-samples.git/.tmp/.goroot/src/code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal/internal_worker_base.go:276
runtime.call32
\t/usr/local/Cellar/go/1.10.2/libexec/src/runtime/asm_amd64.s:573
runtime.gopanic
\t/usr/local/Cellar/go/1.10.2/libexec/src/runtime/panic.go:502
runtime.panicdottypeE
\t/usr/local/Cellar/go/1.10.2/libexec/src/runtime/iface.go:252
runtime.panicdottypeI
\t/usr/local/Cellar/go/1.10.2/libexec/src/runtime/iface.go:262
code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal.getErrorDetails
\t/Users/yiminc/gocode/src/code.uber.internal/devexp/cadence-samples.git/.tmp/.goroot/src/code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal/internal_utils.go:150
code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal.(*workflowTaskHandlerImpl).completeWorkflow
\t/Users/yiminc/gocode/src/code.uber.internal/devexp/cadence-samples.git/.tmp/.goroot/src/code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal/internal_task_handlers.go:1120
code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal.(*workflowExecutionContextImpl).CompleteDecisionTask
\t/Users/yiminc/gocode/src/code.uber.internal/devexp/cadence-samples.git/.tmp/.goroot/src/code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal/internal_task_handlers.go:752
code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal.(*workflowExecutionContextImpl).ProcessWorkflowTask
\t/Users/yiminc/gocode/src/code.uber.internal/devexp/cadence-samples.git/.tmp/.goroot/src/code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal/internal_task_handlers.go:719
code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal.(*workflowTaskHandlerImpl).ProcessWorkflowTask
\t/Users/yiminc/gocode/src/code.uber.internal/devexp/cadence-samples.git/.tmp/.goroot/src/code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal/internal_task_handlers.go:623
code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal.(*workflowTaskPoller).processWorkflowTask
\t/Users/yiminc/gocode/src/code.uber.internal/devexp/cadence-samples.git/.tmp/.goroot/src/code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal/internal_task_pollers.go:231
code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal.(*workflowTaskPoller).ProcessTask
\t/Users/yiminc/gocode/src/code.uber.internal/devexp/cadence-samples.git/.tmp/.goroot/src/code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal/internal_task_pollers.go:211
code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal.(*baseWorker).processTask
\t/Users/yiminc/gocode/src/code.uber.internal/devexp/cadence-samples.git/.tmp/.goroot/src/code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal/internal_worker_base.go:285"}

**Comment by vancexu** [comment]
Fix at https://github.com/uber-go/cadence-client/pull/514.
Include in release v0.7.1
