### ISSUE TITLE
Replay and history mismatch when WorkflowExecutionCompleted

### ISSUE THREAD

**Issue by levicui** [uber-go/cadence-client#527]
**Error**: nondeterministic workflow: missing replay decision for WorkflowExecutionCompleted: (Result:[], DecisionTaskCompletedEventId:34)
**Version of Commit**: 
- package: go.uber.org/cadence
  version: 6f75c62b74d531e4cf4d7c93d9af6403cafe598c

> 
> "stack": "code.uber.internal/odp/goautobots/vendor/go.uber.org/cadence/internal.(*workflowExecutionContextImpl).ProcessWorkflowTask\n\t/home/udocker/goautobots-v2/.tmp/.goroot/src/code.uber.internal/odp/goautobots/vendor/go.uber.org/cadence/internal/internal_task_handlers.go:695\ncode.uber.internal/odp/goautobots/vendor/go.uber.org/cadence/internal.(*workflowTaskHandlerImpl).ProcessWorkflowTask\n\t/home/udocker/goautobots-v2/.tmp/.goroot/src/code.uber.internal/odp/goautobots/vendor/go.uber.org/cadence/internal/internal_task_handlers.go:623\ncode.uber.internal/odp/goautobots/vendor/go.uber.org/cadence/internal.(*workflowTaskPoller).processWorkflowTask\n\t/home/udocker/goautobots-v2/.tmp/.goroot/src/code.uber.internal/odp/goautobots/vendor/go.uber.org/cadence/internal/internal_task_pollers.go:231\ncode.uber.internal/odp/goautobots/vendor/go.uber.org/cadence/internal.(*workflowTaskPoller).ProcessTask\n\t/home/udocker/goautobots-v2/.tmp/.goroot/src/code.uber.internal/odp/goautobots/vendor/go.uber.org/cadence/internal/internal_task_pollers.go:211\ncode.uber.internal/odp/goautobots/vendor/go.uber.org/cadence/internal.(*baseWorker).processTask\n\t/home/udocker/goautobots-v2/.tmp/.goroot/src/code.uber.internal/odp/goautobots/vendor/go.uber.org/cadence/internal/internal_worker_base.go:285"
> 
>     "error": "nondeterministic workflow: missing replay decision for WorkflowExecutionCompleted: (Result:[], DecisionTaskCompletedEventId:34)",
>     "message": "Replay and history mismatch.",

> Domain |   | goautobots-staging-0717
> RunID |   | cab786d1-f1e0-4288-ac78-ead9e041edff
> TaskList |   | goautobots-dsl-wf-task-list-8
> WorkflowID |   | 4bf95ccb-4839-437e-bf47-282b0b3a02c5

I am looking at history to see if i can gather more info.

**Comment by yiminc** [comment]
not repro.
