### ISSUE TITLE
CompleteActivityByID does not return result when error is not nil

### ISSUE THREAD

**Issue by alexDrinkwater** [uber-go/cadence-client#546]
We have some activities that fail/error but still return a result. We would like to be able to access this result after calling CompleteActivityByID however in `RespondActivityTaskFailedByIDRequest` there is no field for result so it can not be set. Is this something that could be added?

**Comment by mfateev** [comment]
It is not possible as it is not supported by the server side API.  I also believe it is Go anti-pattern, so I would recommend encoding additional information into the error itself. Cadence.NewCustomError which accepts additional data details can be used for this.

**Comment by dmetzgar** [comment]
@alexDrinkwater, do you want to keep this issue open?
