### ISSUE TITLE
Retry activity with cleanup

### ISSUE THREAD

**Issue by sagikazarmark** [uber-go/cadence-client#568]
I'm trying to implement a Cadence workflow for the following use case:

Execute a series of steps. If any of the steps fails the workflow should fail as well, but before that, a series of cleanup steps should be executed. The workflow should survive worker restarts.

The last point is a key thing, and to be honest, I find using Cadence a bit cumbersome from this point of view, but it's possible that I don't understand how Cadence works yet.

My first approach was using a RetryPolicy:

```go
	workflow.ActivityOptions{
		ScheduleToStartTimeout: 30 * time.Second,
		StartToCloseTimeout:    1 * time.Minute,
		ScheduleToCloseTimeout: 30 * time.Minute,
		WaitForCancellation:    true,
		RetryPolicy: &cadence.RetryPolicy{
			InitialInterval:          3 * time.Second,
			ExpirationInterval:       3 * time.Minute,
			MaximumAttempts:          3,
			BackoffCoefficient:       1.0,
			NonRetriableErrorReasons: []string{"cadenceInternal:Generic"},
		},
	}
```

This made sure that even if the activity timed out because of a worker restart, it was retried three times.

The only problem with this solution is that I can't decide if an activity will be retried or not, so I cannot execute the cleanup logic.

So my next approach was manually retrying the activity within the workflow  as long as the activity timed out (which appeared in the history as additional workflow runs which is not inherently wrong, but worth noting):

```go
func Workflow(ctx workflow.Context) error {
	ao := workflow.ActivityOptions{
		ScheduleToStartTimeout: 30 * time.Second,
		StartToCloseTimeout:    1 * time.Minute,
		ScheduleToCloseTimeout: 30 * time.Minute,
		WaitForCancellation:    true,
		/*RetryPolicy: &cadence.RetryPolicy{
			InitialInterval:          3 * time.Second,
			ExpirationInterval:       3 * time.Minute,
			MaximumAttempts:          3,
			BackoffCoefficient:       1.0,
			NonRetriableErrorReasons: []string{"cadenceInternal:Generic"},
		},*/
	}

	ctx = workflow.WithActivityOptions(ctx, ao)

	err = workflow.ExecuteActivity(ctx, "activity").Get(ctx, nil)
	for i := 0; i < 3; i++ {
		err = workflow.ExecuteActivity(ctx, "activity").Get(ctx, nil)
		if !cadence.IsTimeoutError(err) {
			break
		}
	}
	if err != nil {
		// do cleanup here

		return err
	}

	return nil
}
```

I'm not fully happy with this solution. As I said I find it a bit cumbersome and I can imagine that I'm doing something totally wrong.

Is there a better way to retry workflows/activities in case of worker restarts (and execute some cleanup steps in case the workflow won't be retried anymore)? Or is my second approach the only way currently to achieve my goal?

Thanks for the help in advance!

**Comment by sagikazarmark** [comment]
@yiminc Thanks for your answer, I probably wasn't completely clear and mixed two things:

- First, I want to make sure that a workflow survives worker restarts. Right now I can do that two ways:
  - High workflow and activity timeout and manual retries in the workflow (eg. when an activity timed out)
  - RetryPolicy, possibly with high maximum attempts and high expiration interval

As far as I can see there is no way to distinct worker restart and "usual" timeouts (like calling an HTTP service took too long). This is what I find a bit cumbersome, because I normally want to retry after all worker restarts, but probably not after all "usual" timeouts.


My other problem is that for some reasons it seemed the cleanup job wouldn't work that way, but I can't really tell you why. I probably looked something over.

Thanks for your help. I would still be curious about your opinion on retrial upon worker restart, but other than that I think this set me on the right course again.

**Comment by mfateev** [comment]
The workflow itself is not affected by worker restarts. All its state is preserved and no action should be taken to handle it. 

An activity is affected by a worker restart which in majority of cases leads to an activity timeout. The RetryOptions apply to the activity execution and by default are going to retry an activity which timed out. If you don't want to retry certain types of errors for them return a custom error created through [cadence.NewCustomError("customErrorReason", ...)](https://github.com/uber-go/cadence-client/blob/master/error.go#L41) and include this "customErrorReason" into NonRetriableErrorReasons.

**Comment by sagikazarmark** [comment]
Thank you @mfateev @yiminc for your answers. I managed to make things work and they make sense after all.
