### ISSUE TITLE
Delayed signals in tests sometimes fire too soon

### ISSUE THREAD

**Issue by Groxx** [uber-go/cadence-client#574]
We've been having occasionally flaky tests, often due to timeouts (so they panic -> very difficult to figure out a cause without logs, due to t.Log behavior), and couldn't identify the cause.
Just yesterday I got lucky and a test failed in a way which produced logs... which showed _all_ our `env.RegisterDelayedCallback(func() { env.SignalWorkflow(...) }, delay)` events occurring before anything in the workflow (e.g. the first activity call).

After a bit of toying around, I managed to get a fairly simple reproduction: https://github.com/Groxx/cadence-client/commit/7bcc1f82e4c01e2649503abd3505c8f8efbe67ad
With 10,000 simultaneous tests it seems fairly reliable on my laptop, but you may need to run it a few times.  I personally like:
```bash
while go test -count 1 -run TestThing ./internal/ ; do echo "retrying" ; done
```
because it'll just keep retrying until it fails, and then it'll stop.

In essence, the test:
- makes a workflow which checks if a signal channel has anything in it, and if not it waits for a value to arrive
- enqueues a signal after a millisecond
  - it DOES seem dependent on this being very small, e.g. I've been unable to repro with time.Second or larger
- sees if it got the signal before it started selecting (which it counts as a failure)

This fails a few times per 10,000 tests.

We've seen several events fire "too soon", with a total delay of several milliseconds, especially on our larger tests, so it doesn't appear to be (only) related to the number of things enqueued.
My guess is that it's somehow related to time between registering delayed callbacks and executing the workflow, but I haven't been able to reproduce it with e.g. a small `time.Sleep` in the test.

---

Obviously this kind of thing can happen IRL, to some degree, and "received a bunch of signals all at once" is a thing that workflows need to be able to handle.  That's totally fine.

The problem is that the test suite isn't deterministic, and that causes occasional test failures.  For now it appears we can work around this with larger (simulated) delays (e.g. I haven't been able to get it to fail with 1 second or more... but I don't see why it'd be *impossible*).  But it feels like it may be worth investigating in case it's due to some kind of bigger problem.

**Comment by yiminc** [comment]
The test framework uses auto forward clock to move forward time (mock clock) and auto fire timers when there is nothing running. This is needed in test environment where you don't want to wait/idle on wall clock for long timer. However, if there is something running (like activity), the mock clock cannot move forward. But, the wall clock will move forward as usual. For example, if your workflow is waiting for a timer of 1s while activity is running, and your activity is running for longer than 1s, the mock clock will not auto forward to fire the timer, because there is something running, however, the wall clock will still move forward and the 1s timer will get fired. 

This is an issue in your case because you use very small interval for the delay, which means there is race condition in your test scenario. In real cadence use case, your timer cannot be less than 1s.

**Comment by Groxx** [comment]
>For example, if your workflow is waiting for a timer of 1s while activity is running, and your activity is running for longer than 1s, the mock clock will not auto forward to fire the timer, because there is something running, however, the wall clock will still move forward and the 1s timer will get fired.

This seems to be implying that e.g. if I set three signals to occur within 1ms of each other, and `time.Sleep(time.Second)` in the code that responds to each (say in each channel's callback, to simulate doing "work"), I should see one arrive, then the sleep starts, then the other two signals, then the other two sleeps.

I tried to cause that in tests, but I wasn't able to - only mocked delays appear to move the RegisterDelayedCallback / mock-clock forward, not actual delays / real time passing.  Regardless of how long I `time.Sleep` in the workflow or e.g. activity it calls, I *usually* see a strict sequence of 1ms mock time elapsed -> signal -> "work" for 1 second -> 1ms mock time elapsed -> signal -> work -> etc, and the end mocked run-time of the test is only 3ms.  Which is what I'd expect - test behavior shouldn't depend on how long the test takes to execute.

**Comment by yiminc** [comment]
You can not use time.Sleep() in the channel's callback. Use workflow.Sleep() instead.

**Comment by yiminc** [comment]
I think I have found the bug, it is related to how we handle the mock due to the limitation of the testify mock. This is a tricky one to fix. Will see what I can do here.

**Comment by Groxx** [comment]
can do.  it's quite easy:
```go
func TestThing2(t *testing.T) {
	s := new(WorkflowTestSuite)
	env := s.NewTestWorkflowEnvironment()
	env.RegisterDelayedCallback(func() { env.SignalWorkflow("sig", "one")}, time.Millisecond)
	env.RegisterDelayedCallback(func() { env.SignalWorkflow("sig", "two")}, 2*time.Millisecond)
	env.RegisterDelayedCallback(func() { env.SignalWorkflow("sig", "three")}, 3*time.Millisecond)
	env.ExecuteWorkflow(ssleep)
	assert.True(t, env.IsWorkflowCompleted())
}

func ssleep(ctx Context) error {
	for i := 0; i < 3; i++ {
		var sig string
		NewSelector(ctx).AddReceive(GetSignalChannel(ctx, "sig"), func(c Channel, more bool) {
			// consume everything in the channel
			for c.ReceiveAsync(&sig) {}
		}).Select(ctx)
		GetLogger(ctx).Info(sig, zap.String("now", Now(ctx).String()))
		time.Sleep(100*time.Millisecond)
	}
	return nil
}
```
logs:
```
=== RUN   TestThing2
2018-09-18T13:32:03.808-0700	DEBUG	internal/internal_workflow_testsuite.go:581	Auto fire timer	{"TimerID": 0, "TimerDuration": "1ms", "TimeSkipped": "1ms"}
2018-09-18T13:32:03.809-0700	INFO	internal/my_test.go:53	one	{"now": "2018-09-18 13:32:03.809314233 -0700 PDT"}
2018-09-18T13:32:03.913-0700	DEBUG	internal/internal_workflow_testsuite.go:581	Auto fire timer	{"TimerID": 1, "TimerDuration": "2ms", "TimeSkipped": "1ms"}
2018-09-18T13:32:03.913-0700	INFO	internal/my_test.go:53	two	{"now": "2018-09-18 13:32:03.810314233 -0700 PDT"}
2018-09-18T13:32:04.015-0700	DEBUG	internal/internal_workflow_testsuite.go:581	Auto fire timer	{"TimerID": 2, "TimerDuration": "3ms", "TimeSkipped": "1ms"}
2018-09-18T13:32:04.015-0700	INFO	internal/my_test.go:53	three	{"now": "2018-09-18 13:32:03.811314233 -0700 PDT"}
```

If workflow.Now was normally impacted by real-world time elapsing, you'd expect the logs to look like `"one", "now": ...:03.8`, then `"three", "now: ...:03.9`, because the second and third signals should've both been sent (and thus available for ReceiveAsync) by the time the second Receive occurred.  And then it'd probably time out the test, since there would be no signal to receive on the third loop.

What you see instead is one emulated millisecond between each event, as if the `time.Sleep` didn't occur, and it receives a single value each time.  Which is what I'd expect, but fails to happen reliably (especially when under high cpu use).

**Comment by yiminc** [comment]
You should not use time.Sleep() within your workflow code. If you replace time.Sleep() with workflow.Sleep() it should work as you expected.

**Comment by Groxx** [comment]
I know - that was a demonstration that wall-clock time *does not* affect the time-skipped values, in response to you saying it *does*.
