### ISSUE TITLE
set MaxConcurrentDecisionTaskExecutionSize to 1 does not work

### ISSUE THREAD

**Issue by yiminc-zz** [uber-go/cadence-client#576]
Set workerOption.MaxConcurrentDecisionTaskExecutionSize = 1 does not work with sticky execution enabled. The minimum needs to be 2 for it to work with sticky. Set to 1 only work if if sticky is disabled.

The problem is when max concurrent decision task is set to 1, we can only have one poller at a time, but there are 2 task lists (one original and one sticky task list).

We should fail NewWorker() when sticky is enabled, and MaxConcurrentDecisionTaskExecutionSize is set to 1. However, NewWorker() does not return error.

**Comment by 14417335** [comment]
reproduced.  when creating worker option, I found this formula is what I needed.  The `MaxConcurrentDecisionTaskExecutionSize` however, has to be set as `2` despite the parallelism I need.
```
	parallelism := 4
	workerOptions := worker.Options{
		MetricsScope:                            h.Scope,
		Logger:                                  h.Logger,
		EnableSessionWorker:                     true,
		MaxConcurrentActivityExecutionSize:      parallelism,
		MaxConcurrentLocalActivityExecutionSize: parallelism,
		MaxConcurrentDecisionTaskExecutionSize:  2,
		MaxConcurrentSessionExecutionSize:       parallelism,
	}
	h.StartWorkers(h.Config.DomainName, ApplicationName, workerOptions)
```
