### ISSUE TITLE
Capability to create WorkflowRun for existing workflow

### ISSUE THREAD

**Issue by samarabbas** [uber-go/cadence-client#621]
Cadence client only supports creation of WorkflowRun through ExecuteWorkflow API.  Although this supports creating a WorkflowRun which could be used to wait on completion of already existing workflow, but there is no way to only support creation of WorkflowRun without first attempting to start the Workflow.
Basically I need an API like below:
```
    GetExecution(ctx context.Context, workflowID string, runID string) (WorkflowRun, error)
```
runID should be optional.

**Comment by mfateev** [comment]
I would name it `GetWorkfowRun` as it returns the `WorkflowRun`.

**Comment by dadgar** [comment]
Just sharing in-case anyone else needs this functionality, the current best practice is calling GetWorkflowHistory with HistoryEventFilterType set to CLOSE_EVENT (from @mfateev in Slack channel).

**Comment by mfateev** [comment]
@dadgar comment applies to Go Client only. The Java one already supports this functionality.
