### ISSUE TITLE
Activity is eaten without any errors(panic) when BackoffCoefficient<1 

### ISSUE THREAD

**Issue by longquanzheng** [uber-go/cadence-client#627]
https://github.com/uber-go/cadence-client/blob/ed836f63720b32c8ea922f1052b222079d4fa4c8/internal/client.go#L294

We only have comments saying "Must be 1 or larger. Default is 2.0." but sometimes people would make mistake. It is better to return error or just panic the request, instead of eating the activities silently.

**Comment by lihannan99** [comment]
Looks like we already have server side validation. 
https://github.com/uber/cadence/blame/326c6bff94fce9e9f07c5d56c2047439414da78a/common/util.go#L378

I will look to see what's need to be done on client side.

**Comment by lihannan99** [comment]
https://github.com/uber-go/cadence-client/blob/edfd47e36473b7c943a59f1e803996986d9ea503/internal/internal_activity.go#L234

**Comment by lihannan99** [comment]
To summarize, we have both server check and client. This error handling was error out in client side code. Customer should get and properly handle the error (for example, by return the error in the workflow). 

```
err := workflow.ExecuteActivity(ctx, batchProcessingActivity, 0, 20, time.Second).Get(ctx, nil)
if err != nil {
	workflow.GetLogger(ctx).Info("Workflow completed with error.", zap.Error(err))
	return err
}
```
