### ISSUE TITLE
Cleanup metrics and logging for client lib

### ISSUE THREAD

**Issue by molteanu** [uber-go/cadence-client#63]
- Add missing metrics
- Remove un-necessary metrics

**Comment by sivakku** [comment]
We need to do additional log cleanup, the debug logs that we emit can confuse the user. we need to hide all these logs.

**Comment by yiminc** [comment]
This is done by:
https://github.com/uber-go/cadence-client/pull/197
https://github.com/uber-go/cadence-client/pull/200
