### ISSUE TITLE
Test with workflow.Go and workflow.Sleep actually sleeps

### ISSUE THREAD

**Issue by recht** [uber-go/cadence-client#647]
When running a test of a workflow that does `workflow.Sleep`, the test normally doesn't actually sleep. However, when combined with `workflow.Go` and an activity that blocks, `Sleep` also blocks until the `Go` activity completes.

Here's a test case that displays the behavior - this emulates something we'd like to do, namely to start a monitor loop which checks for some preconditions, and if they stop being true then interrupt the workflow execution. Of course, we could also do this by starting a child workflow and having that signal back, but I assume this should also work (notice that the sample doesn't include any signalling since that's not the problem here):
```
package versioning

import (
	"context"
	"testing"
	"time"

	"github.com/stretchr/testify/suite"
	"go.uber.org/cadence/activity"
	"go.uber.org/cadence/testsuite"
	"go.uber.org/cadence/workflow"
)

type ts struct {
	suite.Suite
	testsuite.WorkflowTestSuite

	env *testsuite.TestWorkflowEnvironment
}

func (s *ts) SetupTest() {
	s.env = s.NewTestWorkflowEnvironment()
}

func (s *ts) TestSleep() {
	s.env.SetTestTimeout(10 * time.Second)

	a1 := func(ctx context.Context) error {
		ticker := time.NewTicker(1 * time.Second)
		defer ticker.Stop()

		count := 0
		for {
			activity.RecordHeartbeat(ctx)
			s.T().Log("tick", count)
			count++
			select {
			case <-ctx.Done():
				return ctx.Err()
			case <-ticker.C:
				continue
			}
		}
	}

	wf := func(ctx workflow.Context) error {
		ctx, cancel := workflow.WithCancel(ctx)
		defer cancel()

		workflow.Go(ctx, func(ctx workflow.Context) {
			ctx = workflow.WithScheduleToStartTimeout(ctx, 1*time.Second)
			ctx = workflow.WithStartToCloseTimeout(ctx, 1*time.Minute)
			err := workflow.ExecuteActivity(ctx, a1).Get(ctx, nil)
			if err != nil {
				s.T().Log(err)
				return
			}
		})

		workflow.Sleep(ctx, 10*time.Second)
		return nil
	}

	workflow.Register(wf)
	activity.Register(a1)

	s.env.ExecuteWorkflow(wf)
	s.NoError(s.env.GetWorkflowError())
}

func Test(t *testing.T) {
	suite.Run(t, &ts{})
}
```

**Comment by mfateev** [comment]
This is by design. The unit test fast forwards clock every time workflow is blocked and cannot make forward progress. It is done to support unit testing long running workflows.
To verify that clock indeed moved you can compare `s.env.Now()` before and after `s.env.ExecuteWorkflow(wf)` call.
The time is not forwarded while an activity is running as test framework doesn't have any control over activity execution code.

**Comment by mfateev** [comment]
We considered adding activity.Sleep that calls time.Sleep under normal execution and forwards time when running under the a unit test. But I'm not sure if there is a real value in such feature.

**Comment by recht** [comment]
OK, makes sense - so I then have to mock out that activity for the test to be able to run?

**Comment by mfateev** [comment]
Yes, to unit test different workflow code paths mocking activities is the best option. I assume that that you are aware that the `TestWorkflowEnvironment.onActivity` supports mocking directly.

**Comment by recht** [comment]
Yes, I was just trying to write a test that verified that the signalling worked, but I'll just have to mock all of that out.
