### ISSUE TITLE
Keep a Changelog for the Cadence Client?

### ISSUE THREAD

**Issue by hlin117** [uber-go/cadence-client#652]
Hey all! I'm happy to see Cadence-Client is actively maintained. 

It seems the Cadence-Client undergoes code changes pretty frequently. Can we keep a Changelog to document what changes are available version to version?

**Comment by dmetzgar** [comment]
We put all the changes along with the [releases](https://github.com/uber-go/cadence-client/releases). If that doesn't work, could you provide an example of how we could do this better?

**Comment by hlin117** [comment]
Oh I didn't see that! Thank you for linking me. 

As for whether Github release notes or the Changelog format is more standard, I'm not quite the one to say. However, from what I understand from other Uber open source projects like [yarpc-go](https://github.com/uber-go/cadence-client/releases), [thriftrw-go](https://github.com/thriftrw/thriftrw-go/blob/dev/CHANGELOG.md), [zap](https://github.com/uber-go/zap/blob/master/CHANGELOG.md), and the like, the Changelog format seems recommended.

**Comment by dmetzgar** [comment]
In the thrift changelog, it links to [keep a changelog](https://keepachangelog.com) which is pretty informative. I'll have a look.
