### ISSUE TITLE
Add Protobuf support to the default DataConverter

### ISSUE THREAD

**Issue by mfateev** [uber-go/cadence-client#671]
Some of our customers use Protobuf generated structures as workflow and activity inputs and outputs.

**Comment by d-webs** [comment]
+1 Wondering if anybody is actively looking into this. Given the prevalence of Protobuf types in Go APIs this seems like a fairly severe bug.

**Comment by nklijia2011** [comment]
This can also reduce the size of the payload, which can reduce the load Cadence storage layer, and accommodate more workload with same size limit
