### ISSUE TITLE
Support activity renaming 

### ISSUE THREAD

**Issue by mfateev** [uber-go/cadence-client#682]
Currently if activities are moved to another package their names change. it is possible to register their functions with both old and the new name. But it is still is not going to help as existing workflow exectutions that reference function names directly are going to fail with non deterministic change as the new name doesn't match the one recorded in the history.

There is a need for explicit activity aliasing that is replay friendly.

**Comment by ibarrajo** [comment]
This can be done by aliasing the activity during registration.
