### ISSUE TITLE
Return non-deterministic error instead of panicking if side effect not found

### ISSUE THREAD

**Issue by dmetzgar** [uber-go/cadence-client#705]
If a side effect was removed or changed, the current logic is to panic. See [here](https://github.com/uber-go/cadence-client/blob/4ce3f007c2ddda1e8a2cfb858e6c4aceb03752c3/internal/internal_event_handlers.go#L572)

Instead, this should be flagged as a non-deterministic error.

**Comment by mfateev** [comment]
I think if it is removed or changed it has to be protected with Workflow.GetVersion.
