### ISSUE TITLE
Change matchReplayWithHistory to check decisions as they are generated

### ISSUE THREAD

**Issue by mfateev** [uber-go/cadence-client#723]
Currently the matchReplayWithHistory executes after a decision task is processed.
It fails to catch workflow changes that lead to panics as the determinism check never gets chance to execute.

The solution is to check every decision as soon as it is generated.

**Comment by Groxx** [comment]
An example where this is useful, assuming this is v2 (where v1 did something else, and this is NOT a correct change to the workflow code):

```
type Result struct { ... }
func Workflow(ctx workflow.Context) error {
  var result *Result
  err := workflow.ExecuteActivity(ctx, "v2_activity").Get(ctx, &result)
  if err != nil {
    return err
  }
  // assumed to be safe, as the activity always returns err XOR result.
  // the recorded history can confirm this.
  // but in replay, if history changed, this could be a nil from some other activity,
  // leading to result being nil and panicking here without calling it a determinism failure.
  if result.SomeField { ... }
}
```
