### ISSUE TITLE
Add more Selector tests and documentation

### ISSUE THREAD

**Issue by mfateev** [uber-go/cadence-client#734]
Fill up the blanks https://github.com/uber-go/cadence-client/pull/685
Make sure that all of the documented features are unit tested.

**Comment by zmanji** [comment]
Could we please complete this issue?

The lack of comments about the [selector](https://github.com/uber-go/cadence-client/blob/3ac9595c496886bec93959afe51f3d34bd5310e9/internal/workflow.go#L76-L83) API is making it difficult to use.
