### ISSUE TITLE
Add started time to WorkflowInfo

### ISSUE THREAD

**Issue by mfateev** [uber-go/cadence-client#750]
Currently there is no way to find out the workflow start time from the workflow code.
Putting workflow.Now at the beginning doesn't work if the first decision was delayed due to worker downtime.

**Comment by mfateev** [comment]
Also consider other fields recently added to the WorkflowExecutionStarted event

**Comment by ibarrajo** [comment]
Currently not implemented 
https://github.com/uber-go/cadence-client/blob/2d4612d32cf9fd6a0dc45d4e66c2a99492774ee1/internal/workflow.go#L1106-L1129
