### ISSUE TITLE
Notify workflow operations about the termination of a workflow execution

### ISSUE THREAD

**Issue by johncburns1** [uber-go/cadence-client#782]
We are working on the .NET client and are dealing with workflow execution termination at the moment. We noticed that with workflow operations such as workflow.Sleep and activity execution, cancelling the workflow causes cancellation errors to be thrown by any operation called using the parent workflow context because the context has been cancelled. This does not happen with workflow termination. Is there any way to get notified by a running workflow operations of a workflow termination?

We ran into this issue when testing termination on a workflow that just sleeps for 30 seconds (using workflow.Sleep()). We terminate the workflow externally, but workflow.Sleep() never throws an error like it would with cancellation, the workflow just stops scheduling decision tasks. Is there a way to expose the termination of these workflows to operations called with the same parent workflow context?

**Comment by jefflill** [comment]
...we need this for the .NET client we're working on that currently wraps the GO Cadence client.  Ideally, we'd like to see some kind of notification when the local worker has been directed to terminate a running workflow.  We'd handle this notification by sending a message to the .NET client so it will be able terminate the workflow running on that side.

**Comment by mfateev** [comment]
Add defer into the main workflow function. It is always called even when a workflow cleaned up from worker memory.

**Comment by johncburns1** [comment]
Some code samples for reference:
### main.go
```
func main() {

	// setup the SampleHelper
	var h common.SampleHelper
	h.SetupServiceConfig()

	// start the worker
	// execute the workflow
	workflowWorker := startWorkers(&h)
	workflowRun := startWorkflow(&h)

	// build the workflow client
	workflowClient, err := h.Builder.BuildCadenceClient()
	if err != nil {
		panic(err)
	}

	// create the context
	ctx, cancel := context.WithCancel(context.Background())
	time.Sleep(time.Second * 5)

	// externally terminate workflow
	//err = workflowClient.TerminateWorkflow(ctx, workflowRun.GetID(), workflowRun.GetRunID(), "terminate", []byte{0, 1, 2, 3, 4})
	err = workflowClient.TerminateWorkflow(ctx, workflowRun.GetID(), workflowRun.GetRunID(), "terminate-test", []byte{0, 1, 2, 3, 4})
	if err != nil {
		panic(err)
	}

	time.Sleep(time.Second * 5)

	resp, err := workflowClient.DescribeWorkflowExecution(ctx, workflowRun.GetID(), workflowRun.GetRunID())
	if err != nil {
		panic(err)
	}

	// log response
	h.Logger.Debug("Resp", zap.Any("Execution Info", *resp))

	// create context to
	// get the workflow result
	var result string
	err = workflowRun.Get(ctx, &result)
	if err != nil {
		h.Logger.Error("workflow failed", zap.Error(err))
	} else {
		h.Logger.Info("Workflow Completed", zap.String("Result", result))
	}

	// stop the worker
	// cancel the context
	workflowWorker.Stop()
	cancel()
}
```

### greetings_workflow.go
```
func SampleGreetingsWorkflow(ctx workflow.Context) (string, error) {

	// workflow sleep
	var err error
	logger := workflow.GetLogger(ctx)
	err = workflow.Sleep(ctx, time.Second*30)
	if err != nil {
		logger.Error("Sleep failed", zap.Error(err))
		return "", err
	}

	return "success", nil
}
```
