### ISSUE TITLE
Allow ReplayWorkflowHistoryFromJSONFile invoking activities

### ISSUE THREAD

**Issue by mfateev** [uber-go/cadence-client#811]
Provide a method similar to ReplayWorkflowHistoryFromJSONFile that invokes activities ignoring their results. this can be useful in some debugging situations.

**Comment by mfateev** [comment]
Proposal is to have ReplayActivityFromJSONFile given the file and the eventID of the ActivityTaskScheduled event.

**Comment by woniesong92** [comment]
:+1:
