### ISSUE TITLE
workflow.IsReplaying == FALSE when workflow is replayed

### ISSUE THREAD

**Issue by jefflill** [uber-go/cadence-client#821]
While testing replay behavior on the .NET client and we're not seeing the behavior I expect when the workflow returns an error.

The workflow below returns prints out the replay status.  For the first attempt, `workflow.IsReplaying(ctx)` returns `false` as expected.  I then exit the first run with an error.  The workflow starts it's second attempt and `IsReplaying()==false`, which I didn't expect.  Are we doing this check incorrectly?

I also tried sleeping long enough to exceed the decision task timeout for the first attempt and am seeing the same behavior.

Here's the code:

```
package main

import (
	"context"
	"errors"
	"fmt"
	"time"

	"go.uber.org/cadence"
	"go.uber.org/cadence/activity"
	"go.uber.org/cadence/client"
	"go.uber.org/cadence/worker"
	"go.uber.org/cadence/workflow"
	"go.uber.org/zap"

	"github.com/pborman/uuid"

	"github.com/cadence-proxy/cmd/playground/common"
)

func main() {

	// setup the SampleHelper
	var h common.SampleHelper
	h.SetupServiceConfig()

	// start the worker
	// execute the workflow
	workflowWorker := startWorkers(&h)
	workflowRun := startWorkflow(&h)

	// build the workflow client
	workflowClient, err := h.Builder.BuildCadenceClient()
	if err != nil {
		panic(err)
	}

	// create the context
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	// describe the workflow execution
	resp, err := workflowClient.DescribeWorkflowExecution(ctx, workflowRun.GetID(), workflowRun.GetRunID())
	if err != nil {
		panic(err)
	}

	// log response
	h.Logger.Debug("Resp", zap.Any("Execution Info", *resp))

	// create context to
	// get the workflow result
	var result string
	err = workflowRun.Get(ctx, &result)
	if err != nil {
		h.Logger.Error("workflow failed", zap.Error(err))
	} else {
		h.Logger.Info("Workflow Completed", zap.String("Result", result))
	}

	// stop the worker
	workflowWorker.Stop()
}

//-----------------------------------------------------------------------------
// Test workflow and activity

const ApplicationName = "simpleGroup"

func init() {
	workflow.Register(ReplayWorkflow)
	activity.Register(getNameActivity)
}

var firstRun = true

func ReplayWorkflow(ctx workflow.Context) (string, error) {

	fmt.Println("----------")

	if firstRun {
		fmt.Println("FIRST RUN")
	} else {
		fmt.Println("SECOND RUN")
	}

	if workflow.IsReplaying(ctx) {
		fmt.Println("IsReplaying: TRUE")
	} else {
		fmt.Println("IsReplaying: FALSE")
	}

	if firstRun {
		firstRun = false
		//time.Sleep(time.Second * 12)
		return "", errors.New("Force replay.")
	}

	fmt.Println("SLEEPING...")
	workflow.Sleep(ctx, time.Second)

	if workflow.IsReplaying(ctx) {
		fmt.Println("IsReplaying: TRUE")
	} else {
		fmt.Println("IsReplaying: FALSE")
	}

	return "Completed", nil
}

func getNameActivity() (string, error) {
	return "Cadence", nil
}

//-----------------------------------------------------------------------------
// Helpers

// This needs to be done as part of a bootstrap step when the process starts.
// The workers are supposed to be long running.
func startWorkers(h *common.SampleHelper) worker.Worker {
	// Configure worker options.
	workerOptions := worker.Options{
		MetricsScope: h.Scope,
		Logger:       h.Logger,
	}
	return h.StartWorkers(h.Config.DomainName, ApplicationName, workerOptions)
}

func startWorkflow(h *common.SampleHelper) client.WorkflowRun {

	workflowOptions := client.StartWorkflowOptions{
		ID:                              "simple_" + uuid.New(),
		TaskList:                        ApplicationName,
		ExecutionStartToCloseTimeout:    time.Minute,
		DecisionTaskStartToCloseTimeout: time.Second * 10,
		RetryPolicy: &cadence.RetryPolicy{
			InitialInterval:    time.Second,
			BackoffCoefficient: 1.0,
			MaximumInterval:    time.Second,
			ExpirationInterval: time.Minute,
			MaximumAttempts:    2},
	}

	return h.StartWorkflow(workflowOptions, ReplayWorkflow)
}
```

**Comment by jefflill** [comment]
**NOTE:** We need this so the .NET client will be able to avoid doing logging and metrics during replay.

**Comment by mfateev** [comment]
This code is not expected to work at all as it is not deterministic. Returning an error from the workflow function doesn't force replay. It just fails the workflow. To force replay I would recommend just turning off sticky execution (don't do it in production) by setting the corresponding worker option and calling workflow.Sleep(ctx, time.Second).

**Comment by mfateev** [comment]
Another way to force replay is panic. Try changing` return "", errors.New("Force replay.") `to `panic("force replay")`

**Comment by jefflill** [comment]
OK: Yeah, I know this isn’t deterministic.  I was trying a simple case to replicate the behavior.

I think I may not understand how RetryPolicy works.  If I have a policy set to retry and then the workflow returns an error what happens?

I assumed that the error would cause the workflow to fail and that it would replay up to the decision task that failed and then start doing new work thereafter.  It sounds like the workflow will start over from the beginning (not replaying), is this correct?

That doesn’t seem super idempotent though.  It seems like you could have a workflow that does a bunch of stuff and then times out in an activity that couldn’t write to a DB or something due to transient issues.  Does this mean that the entire workflow would run again?

What I was hoping to do was write workflow tests that I could progressively fail at each step and then verify that during the replayed steps that the the various replayed operations returned the same values that were returned the first time they were run.

I’ll give your disable-sticky/sleep technique a shot tomorrow.  That’ll be cleaner than returning errors.

**Comment by mfateev** [comment]
If a workflow that has a retry policy fails it is marked as failed and the new run of the workflow is created with the same input and other initial parameters as the initial run. This new run doesn't have a decision task scheduled until the next retry interval. Then after the specified delay the decision task is created and the workflow starts execution. Note that in this case there is no replay. The new workflow starts execution from the beginning as a new workflow instance. It explains the results you are seeing.

**Comment by jefflill** [comment]
Thanks.  That makes sense.  I haven’t really tested error scenarios until now.

**Comment by jefflill** [comment]
@mfateev: I just verified that disabling sticky execution causes every step to replay.  I think I'll be able to structure my unit tests to work with this behavior,  **Thanks!**

**One question:** I'm a little surprised that exceeding the decision task timeout doesn't cause a the workflow to replay and causes the workflow to fail instead.  I could see the potential for the CPU to be busy on the worker or RAM filling up causing excessive swapping while executing a workflow causing the decision task timeout to be exceeded in rare situations.

Does this ever happen in real life or does Cadence have another way of dealing with these cases?

**Comment by mfateev** [comment]
Exceeding the decision task timeout causes the decision task rescheduling and workflow continues without problem. Without this behavior any worker failure would lead to workflow failures. Note that even panic during workflow execution doesn't lead to workflow failure by default. It just blocks the workflow execution (by constantly failing decision tasks) until the bug is fixed.

In your initial example the workflow failed not because of the decision task timeout, but because you explicitly failed it by returning an error from the workflow function.

**Comment by jefflill** [comment]
Gotcha.

**Comment by jefflill** [comment]
We're still experiencing problems with this.  It looks like the GOLANG client doesn't report `IsReplaying=TRUE` unless the workflow already has something recorded to history.

In the sample below, the `ReplayWorkflow` function implements the test workflow, and I'm calling `panic()` to cause a replay (stick cache is enabled).  The workflow as coded above reports `IsReplaying=FALSE` the first time the function is called which panics.  Then it also reports the `IsReplaying=FALSE` for the second call.
```
package main

import (
	"context"
	"fmt"
	"time"

	"go.uber.org/cadence"
	"go.uber.org/cadence/activity"
	"go.uber.org/cadence/client"
	"go.uber.org/cadence/worker"
	"go.uber.org/cadence/workflow"
	"go.uber.org/zap"

	"github.com/pborman/uuid"

	"github.com/cadence-proxy/cmd/playground/common"
)

func main() {

	// setup the SampleHelper
	var h common.SampleHelper
	h.SetupServiceConfig()

	// start the worker
	// execute the workflow
	workflowWorker := startWorkers(&h)
	workflowRun := startWorkflow(&h)

	// build the workflow client
	workflowClient, err := h.Builder.BuildCadenceClient()
	if err != nil {
		panic(err)
	}

	// create the context
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	// describe the workflow execution
	resp, err := workflowClient.DescribeWorkflowExecution(ctx, workflowRun.GetID(), workflowRun.GetRunID())
	if err != nil {
		panic(err)
	}

	// log response
	h.Logger.Debug("Resp", zap.Any("Execution Info", *resp))

	// create context to
	// get the workflow result
	var result string
	err = workflowRun.Get(ctx, &result)
	if err != nil {
		h.Logger.Error("workflow failed", zap.Error(err))
	} else {
		h.Logger.Info("Workflow Completed", zap.String("Result", result))
	}

	// stop the worker
	workflowWorker.Stop()
}

//-----------------------------------------------------------------------------
// Test workflow and activity

const ApplicationName = "simpleGroup"

func init() {
	workflow.Register(ReplayWorkflow)
	activity.Register(TestActivity)
}

var firstRun = true

func ReplayWorkflow(ctx workflow.Context) (string, error) {

	fmt.Println("==================================")
	printRun()
	printReplayStatus(ctx)

	if firstRun {
		firstRun = false
		forceReplay(ctx)
	}

	fmt.Println("Calling activity #1")
	testActivity(ctx, "#1")
	printReplayStatus(ctx)

	// if firstRun {
	// 	firstRun = false
	// 	forceReplay(ctx)
	// }

	fmt.Println("Calling activity #2")
	testActivity(ctx, "#3")
	printReplayStatus(ctx)

	return "Completed", nil
}

func printRun() {
	fmt.Println("----------")
	if firstRun {
		fmt.Println("FIRST RUN")
	} else {
		fmt.Println("SECOND RUN")
	}
}

func printReplayStatus(ctx workflow.Context) {
	if workflow.IsReplaying(ctx) {
		fmt.Println("IsReplaying: TRUE")
	} else {
		fmt.Println("IsReplaying: FALSE")
	}
}

func forceReplay(ctx workflow.Context) {
	fmt.Println("*** Force Replay ***")
	//workflow.Sleep(ctx, 0)
	//workflow.NewTimer(ctx, 0).Get(ctx, nil)
	panic("Force Replay")
	//fmt.Println("*** Force DONE ***")
}

func TestActivity(ctx context.Context, value string) (string, error) {
	return value, nil
}

//-----------------------------------------------------------------------------
// Helpers

// This needs to be done as part of a bootstrap step when the process starts.
// The workers are supposed to be long running.
func startWorkers(h *common.SampleHelper) worker.Worker {
	// Configure worker options.
	workerOptions := worker.Options{
		MetricsScope:           h.Scope,
		Logger:                 h.Logger,
		DisableStickyExecution: false,
	}
	return h.StartWorkers(h.Config.DomainName, ApplicationName, workerOptions)
}

func startWorkflow(h *common.SampleHelper) client.WorkflowRun {

	workflowOptions := client.StartWorkflowOptions{
		ID:                              "simple_" + uuid.New(),
		TaskList:                        ApplicationName,
		ExecutionStartToCloseTimeout:    time.Minute,
		DecisionTaskStartToCloseTimeout: time.Second * 10,
		RetryPolicy: &cadence.RetryPolicy{
			InitialInterval:    time.Second,
			BackoffCoefficient: 1.0,
			MaximumInterval:    time.Second,
			ExpirationInterval: time.Minute,
			MaximumAttempts:    2},
	}

	return h.StartWorkflow(workflowOptions, ReplayWorkflow)
}

func testActivity(ctx workflow.Context, value string) (string, error) {

	var result string
	var err error

	ao := workflow.ActivityOptions{
		ScheduleToCloseTimeout: time.Second * 60,
		ScheduleToStartTimeout: time.Second * 60,
		StartToCloseTimeout:    time.Second * 60,
		HeartbeatTimeout:       time.Second * 10,
		WaitForCancellation:    false,
	}

	ctx = workflow.WithActivityOptions(ctx, ao)
	future := workflow.ExecuteActivity(ctx, TestActivity, value)
	err = future.Get(ctx, &result)

	return result, err
}
```
If I comment out the first `if firstRun {...}`  statement and uncomment the second one (after the first activity call), the workflow function will immediately report `IsReplaying=TRUE`, as expected.

We're going to `IsReplaying` to control when we log events and metrics.  With the existing behavior, if a workflow logs something when it's first called and then fails and is restarted before the first activity (or something that records to history) is invoked, then when the workflow restarts, we'd log the same thing again, even though the workflow is effectively replaying.

We could work around this by calling an internal local activity at the beginning of every .NET workflow which would probably work in most circumstances but it would be unfortunate to have this show up in the Cadence UX/history.

...or perhaps, I don't understand what `IsReplaying` actually means.

**Comment by mfateev** [comment]
This is by design. By panicing you fail the decision task which means that workflow didn't make any progress and nothing is recorded in the history. So when the task is reexecuted it is treated as an initial task so it is not replay as the code is executed for the first time.

I'm not sure what is your goal. The workflow code should never panic unless there is a serious bug that should block the workflow progress until it is fixed.

**Comment by mfateev** [comment]
Panic in Go is not the same as an exception in C# or Java. It is not expected to be used unless there is a catastrophic failure. https://blog.golang.org/error-handling-and-go

**Comment by jefflill** [comment]
Yep, I'm aware of how panics work.

I've been implementing unit tests on the .NET side where I can force a workflow to replay and then verify that I'm seeing the expected behavior like `IsReplaying` being set properly and also that I'm seeing the same values when operations are being replayed that were returned the first time the operations were performed.  These tests are important because had to actively do work to expose what's happening on the GO side to .NET.

You suggested above that calling `panic()` in the workflow function would cause the workflow to be replayed and that does seem to be working as expected with the exception that `IsReplaying=FALSE` when there's nothing in the history which seemed a bit odd so I figured I'd report it.

It's not a huge deal, but it will mean that a .NET workflow that logs something at the start and then is replayed before it has a chance to do something that writes to history, will log the same thing again the when it is rescheduled.  I imagine that this will occur very rarely in real life.

I presume the GO and perhaps Java client would do the same thing in this scenario, since this is by design.  I'll go ahead and close this again since the .NET client will behave the same as the others.
