### ISSUE TITLE
Integrate With New Get History Raw API

### ISSUE THREAD

**Issue by wxing1292** [uber-go/cadence-client#857]
Integrate with the new get raw history API, since currently on the server side the history events are deserialized when loaded from DB and serialized again when dispatching to client.

Server side corresponding issue: https://github.com/uber/cadence/issues/2644

**Comment by mkolodezny** [comment]
https://github.com/uber/cadence/pull/3463

**Comment by mkolodezny** [comment]
https://github.com/uber-go/cadence-client/pull/1019
