### ISSUE TITLE
QueryWorkflow in unit test

### ISSUE THREAD

**Issue by jc-fireball** [uber-go/cadence-client#865]
In unit test, the QueryWorkflow can only be used when the test workflow is running. If the workflow stops, the QueryWorkflow won't work.

**Comment by Groxx** [comment]
a Q since I haven't tried this:
I'd think QueryWorkflow should be called in tests in a delayed callback, since you'll need to execute it at some simulated time.  does it work within there?

**Comment by mfateev** [comment]
I believe it works from the delayed callback. This issue is to support it working after ExecuteWorkflow returns.
