### ISSUE TITLE
Resetting workflow with Searchable Attributes causes non-deterministic error

### ISSUE THREAD

**Issue by samarabbas** [uber-go/cadence-client#867]
- Modify searchable attribute sample to not pass in searchable attribute on start
- Add an activity between 2 searchable attributes.  https://pastebin.com/AcBkWTDZ
- Run the workflow
- reset workflow to event id 11

This results in non-deterministic error.  
Make sure to run the sample latest client release.

**Comment by samarabbas** [comment]
Looks like replay decision is getting corrupted when no searchable attributes are passed in when starting workflow.  For now pass in a dummy Searchable Attribute to workaround this issue.

**Comment by vancexu** [comment]
This is fixed as part of https://github.com/uber-go/cadence-client/pull/889. 
Will be released in v0.10.1
