### ISSUE TITLE
Test support for SideEffect

### ISSUE THREAD

**Issue by vancexu** [uber-go/cadence-client#869]
Currently, user with following code 
```
encodedRandom := workflow.SideEffect(func(ctx cadence.Context) interface{} {
        return uuid.NewV4().String()
})
var id int
err := encodedRandom.Get(&id)
if err != nil {
  return err
}
```

have no easy way to test line `err := encodedRandom.Get(&id) if err ...` for full test coverage.

Need to add support for it, at least through mock.

**Comment by mfateev** [comment]
In the above case error comes from the decoding, not from the sideEffect. So in the above code error is not really possible as the returned type cannot really change from String to anything else.

**Comment by vancexu** [comment]
I agree above code error is not really possible, 
my original thought on having a test API OnSideEffect to return a `mock.Value` is overkill. 
Closed as invalid.
