### ISSUE TITLE
"make bins" is broken with golint errors

### ISSUE THREAD

**Issue by mfateev** [uber-go/cadence-client#875]
maxpro:cadence maxim$ git clone https://github.com/uber-go/cadence-client.git
Cloning into 'cadence-client'...
remote: Enumerating objects: 31, done.
remote: Counting objects: 100% (31/31), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 5869 (delta 5), reused 20 (delta 1), pack-reused 5838
Receiving objects: 100% (5869/5869), 4.86 MiB | 15.46 MiB/s, done.
Resolving deltas: 100% (4007/4007), done.
maxpro:cadence maxim$ cd cadence-client/

maxpro:cadence-client maxim$ make bins
./versioned_go_build.sh go.uber.org/thriftrw v1.11.0 .bins/versions/thriftrw-v1.11.0
	go.uber.org/thriftrw has a newer tag: v1.20.2
./versioned_go_build.sh go.uber.org/yarpc v1.29.1 encoding/thrift/thriftrw-plugin-yarpc .bins/versions/yarpc-v1.29.1
	go.uber.org/yarpc has a newer tag: v1.42.0
thriftrw: idl/github.com/uber/cadence/cadence.thrift
PATH=".bins" .bins/thriftrw --plugin=yarpc --pkg-prefix=go.uber.org/cadence/.gen/go --out=.gen/go idl/github.com/uber/cadence/cadence.thrift;
go run ./internal/cmd/tools/copyright/licensegen.go --verifyOnly
./versioned_go_build.sh golang.org/x/lint 470b6b0bb3005eda157f0275e2e4895055396a81 golint .bins/versions/golint-470b6b0bb3005eda157f0275e2e4895055396a81
	golang.org/x/lint is 14 commits behind the current HEAD: 16217165b5de779cb6a5e4fc81fa9c1166fda457
test -n "./version.go ./error.go ./cadence.go" && .bins/golint -set_exit_status ./version.go ./error.go ./cadence.go || ERR=1;   test -n "./activity/activity.go ./activity/doc.go" && .bins/golint -set_exit_status ./activity/activity.go ./activity/doc.go || ERR=1;   test -n "./client/client.go" && .bins/golint -set_exit_status ./client/client.go || ERR=1;   test -n "./encoded/encoded.go" && .bins/golint -set_exit_status ./encoded/encoded.go || ERR=1;   test -n "./evictiontest/workflow_cache_eviction_test.go" && .bins/golint -set_exit_status ./evictiontest/workflow_cache_eviction_test.go || ERR=1;   test -n "./internal/internal_task_handlers.go ./internal/internal_event_handlers_test.go ./internal/internal_event_handlers.go ./internal/internal_activity.go ./internal/internal_workflow_client.go ./internal/version.go ./internal/error.go ./internal/internal_utils_test.go ./internal/encoded.go ./internal/internal_coroutines_test.go ./internal/worker.go ./internal/internal_workers_test.go ./internal/internal_public.go ./internal/headers_test.go ./internal/internal_worker.go ./internal/internal_decision_state_machine.go ./internal/workflow_testsuite_test.go ./internal/session.go ./internal/tracer_test.go ./internal/internal_workflow_testsuite_test.go ./internal/activity.go ./internal/internal_logging_tags.go ./internal/internal_workflow_client_test.go ./internal/client.go ./internal/internal_worker_base.go ./internal/activity_test.go ./internal/internal_utils.go ./internal/internal_worker_interfaces_test.go ./internal/internal_retry.go ./internal/internal_task_pollers.go ./internal/internal_task_handlers_test.go ./internal/context.go ./internal/propagation.go ./internal/internal_workflow_testsuite.go ./internal/internal_task_handlers_interfaces_test.go ./internal/workflow_testsuite.go ./internal/internal_workflow.go ./internal/internal_time.go ./internal/internal_decision_state_machine_test.go ./internal/session_test.go ./internal/error_test.go ./internal/tracer.go ./internal/internal_workflow_test.go ./internal/internal_worker_test.go ./internal/encoded_test.go ./internal/internal_pressure_points.go ./internal/headers.go ./internal/workflow.go" && .bins/golint -set_exit_status ./internal/internal_task_handlers.go ./internal/internal_event_handlers_test.go ./internal/internal_event_handlers.go ./internal/internal_activity.go ./internal/internal_workflow_client.go ./internal/version.go ./internal/error.go ./internal/internal_utils_test.go ./internal/encoded.go ./internal/internal_coroutines_test.go ./internal/worker.go ./internal/internal_workers_test.go ./internal/internal_public.go ./internal/headers_test.go ./internal/internal_worker.go ./internal/internal_decision_state_machine.go ./internal/workflow_testsuite_test.go ./internal/session.go ./internal/tracer_test.go ./internal/internal_workflow_testsuite_test.go ./internal/activity.go ./internal/internal_logging_tags.go ./internal/internal_workflow_client_test.go ./internal/client.go ./internal/internal_worker_base.go ./internal/activity_test.go ./internal/internal_utils.go ./internal/internal_worker_interfaces_test.go ./internal/internal_retry.go ./internal/internal_task_pollers.go ./internal/internal_task_handlers_test.go ./internal/context.go ./internal/propagation.go ./internal/internal_workflow_testsuite.go ./internal/internal_task_handlers_interfaces_test.go ./internal/workflow_testsuite.go ./internal/internal_workflow.go ./internal/internal_time.go ./internal/internal_decision_state_machine_test.go ./internal/session_test.go ./internal/error_test.go ./internal/tracer.go ./internal/internal_workflow_test.go ./internal/internal_worker_test.go ./internal/encoded_test.go ./internal/internal_pressure_points.go ./internal/headers.go ./internal/workflow.go || ERR=1;   test -n "./internal/cmd/dummy/dummy.go" && .bins/golint -set_exit_status ./internal/cmd/dummy/dummy.go || ERR=1;   test -n "./internal/cmd/tools/copyright/licensegen.go" && .bins/golint -set_exit_status ./internal/cmd/tools/copyright/licensegen.go || ERR=1;   test -n "./internal/common/thrift_util.go ./internal/common/convert.go" && .bins/golint -set_exit_status ./internal/common/thrift_util.go ./internal/common/convert.go || ERR=1;   test -n "./internal/common/backoff/retrypolicy_test.go ./internal/common/backoff/retry_test.go ./internal/common/backoff/retrypolicy.go ./internal/common/backoff/retry.go" && .bins/golint -set_exit_status ./internal/common/backoff/retrypolicy_test.go ./internal/common/backoff/retry_test.go ./internal/common/backoff/retrypolicy.go ./internal/common/backoff/retry.go || ERR=1;   test -n "./internal/common/cache/lru_test.go ./internal/common/cache/cache.go ./internal/common/cache/lru.go" && .bins/golint -set_exit_status ./internal/common/cache/lru_test.go ./internal/common/cache/cache.go ./internal/common/cache/lru.go || ERR=1;   test -n "./internal/common/metrics/scope_test.go ./internal/common/metrics/constants.go ./internal/common/metrics/capturingStatsReporter.go ./internal/common/metrics/service_wrapper.go ./internal/common/metrics/service_wrapper_test.go ./internal/common/metrics/scope.go" && .bins/golint -set_exit_status ./internal/common/metrics/scope_test.go ./internal/common/metrics/constants.go ./internal/common/metrics/capturingStatsReporter.go ./internal/common/metrics/service_wrapper.go ./internal/common/metrics/service_wrapper_test.go ./internal/common/metrics/scope.go || ERR=1;   test -n "./internal/common/util/util.go ./internal/common/util/stringer_test.go ./internal/common/util/stringer.go" && .bins/golint -set_exit_status ./internal/common/util/util.go ./internal/common/util/stringer_test.go ./internal/common/util/stringer.go || ERR=1;   test -n "./test/test_utils.go ./test/activity_test.go ./test/workflow_test.go ./test/integration_test.go" && .bins/golint -set_exit_status ./test/test_utils.go ./test/activity_test.go ./test/workflow_test.go ./test/integration_test.go || ERR=1;   test -n "./testsuite/testsuite.go" && .bins/golint -set_exit_status ./testsuite/testsuite.go || ERR=1;   test -n "./worker/worker.go" && .bins/golint -set_exit_status ./worker/worker.go || ERR=1;   test -n "./workflow/error.go ./workflow/session.go ./workflow/deterministic_wrappers.go ./workflow/context_propagator.go ./workflow/doc.go ./workflow/workflow_options.go ./workflow/context.go ./workflow/activity_options.go ./workflow/workflow.go" && .bins/golint -set_exit_status ./workflow/error.go ./workflow/session.go ./workflow/deterministic_wrappers.go ./workflow/context_propagator.go ./workflow/doc.go ./workflow/workflow_options.go ./workflow/context.go ./workflow/activity_options.go ./workflow/workflow.go || ERR=1;  test -z "$ERR" || exit 1
./client/client.go:392:2: comment on exported const ParentClosePolicyTerminate should be of the form "ParentClosePolicyTerminate ..."
./client/client.go:394:2: comment on exported const ParentClosePolicyRequestCancel should be of the form "ParentClosePolicyRequestCancel ..."
./client/client.go:396:2: comment on exported const ParentClosePolicyAbandon should be of the form "ParentClosePolicyAbandon ..."
Found 3 lint suggestions; failing.
./internal/client.go:462:2: comment on exported const ParentClosePolicyTerminate should be of the form "ParentClosePolicyTerminate ..."
./internal/client.go:464:2: comment on exported const ParentClosePolicyRequestCancel should be of the form "ParentClosePolicyRequestCancel ..."
./internal/client.go:466:2: comment on exported const ParentClosePolicyAbandon should be of the form "ParentClosePolicyAbandon ..."
Found 3 lint suggestions; failing.
make: *** [lint] Error 1
maxpro:cadence-client maxim$

**Comment by mfateev** [comment]
I would recommend adding "make bins" to the buildkite validation build.

**Comment by mfateev** [comment]
Or at least run linter on make.

**Comment by Groxx** [comment]
can probably close this?  it's passing for me fwiw

**Comment by mfateev** [comment]
Let's keep this open until linter errors are caught by the buildkite.
