### ISSUE TITLE
Add size protections

### ISSUE THREAD

**Issue by andrewjdawson2016** [uber-go/cadence-client#877]
We found that that customers can bring cadence server down by sending large requests to it. These large requests get buffered in yarpc and cause memory issues for cadence. 

Just dropping these on the server is not enough, we actually need client side protection against this.

**Comment by luowenking1** [comment]
Query is already handled, do we want to also add protections for decisions?

**Comment by luowenking1** [comment]
@venkat1109 suggested we do not need to work on this task anymore.
