### ISSUE TITLE
Question: Canceling workflows with client.CancelWorkflow

### ISSUE THREAD

**Issue by tscolari** [uber-go/cadence-client#920]
Hello!

I'm running on some issues when trying to cancel a workflow here.
Pretty much I've 2 workflows: one to create and one to destroy.

On my destroy workflow I want to signal the creation one to cancel, I'm using the client for that and it seems to work correctly - if the create workflow is running. Otherwise, it blocks "forever".

What would be the recommended approach here?
I thought about checking if the workflow is running beforehand but this is will cause a race condition.

**Comment by mfateev** [comment]
it doesn't sound right. One possible explanation is that the client retries the exception thrown when workflow is not found for a long time. 

As a workaround consider having one workflow that performs both operations.

**Comment by tscolari** [comment]
Thanks for getting back, you're absolutely right!
I've just checked and it's actually the activity retrying because the Cancel returned a EntityNotExistsError. I'm now correctly looking for this, and it is working as expected :)
