### ISSUE TITLE
Need API to signal self 

### ISSUE THREAD

**Issue by longquanzheng** [uber-go/cadence-client#927]
We have a SignalExternalWorkflows which disallows sending signals to self. We need to have an API to signal to self. Ideally it should be implemented in a more efficient way that doesn't need multiple round trips -- just put a signal as DecisionTaskCompleted. 

See https://github.com/uber-go/cadence-client/pull/924 for more information.

**Comment by mfateev** [comment]
I think sending signal to itself is an exception which is not worth optimizing. So just allowing own ID in the SignalExternalWorkflows should be enough IMHO.
