### ISSUE TITLE
Workflow stuck when calling `workflow.GetVersion`

### ISSUE THREAD

**Issue by seriousben** [uber-go/cadence-client#931]
Calling `GetVersion` results in a loop / weird behavior on the cadence server and the worker.

### Code causing the behavior:
```
workflow.GetVersion(ctx, "step1", workflow.DefaultVersion, 1)

... rest of workflow
```

### Cadence UI Screenshot:

<img width="1209" alt="image" src="https://user-images.githubusercontent.com/6145422/72834701-5b4fd000-3c57-11ea-8f3e-3e3562c39696.png">

Error in text:
```
Could not parse body (arg3) argument. Expected Thrift encoded arg3 for endpoint WorkflowService::GetWorkflowExecutionHistory. Got    instead of Thrift. Parsing error was: value must be a valid member of enumeration DecisionTaskFailedCause, got: 22.
```

### Cadence server logs:

```
"msg":"invalid search attribute","service":"cadence-history","component":"shard-controller","shard-id":2,"component":"history-engine","es-mapping-key":"CadenceChangeVersion","wf-domain-name":"<redacted>","logging-call-at":"searchAttrValidator.go:79"
"msg":"Failing the decision.","service":"cadence-history","component":"shard-controller","shard-id":2,"component":"history-engine","wf-decision-fail-cause":22,"wf-id":"<redacted>","wf-run-id":"6f535980-dbd6-4731-8ea8-c9d2bd6566e5","wf-domain-id":"73e5c82e-d45f-4de6-95f4-25b5ce00f9bb","logging-call-at":"decisionHandler.go:447"
```

### Versions:

__Cadence server:__
* Configured to use MySQL
* `ubercadence/server:0.10.3-auto-setup`

__Cadence client:__
* `go.uber.org/cadence v0.10.5`

---

The bug was initially reported on slack: https://uber-cadence.slack.com/archives/CM4K75Y7R/p1579622445006800

**Comment by martinxsliu** [comment]
I ran into a similar issue with adding GetVersion for the first time. Downgrading the client version from `0.10.5` to `0.9.3` worked (with server version `0.7.1`)

**Comment by seriousben** [comment]
I was able to reproduce this bug with the samples: https://github.com/uber-common/cadence-samples/compare/master...seriousben:reproduce-get-version-bug?expand=1

**Comment by vancexu** [comment]
Thanks @seriousben for reporting this. 
1. We will release Cadence server 0.11 this week, and it contains a fix for the errors you mentioned.
2. Were you able to view history using CLI? If so it is a web issue only and @just-at-uber can you help this. (we may just need a release of Cadence Web)

**Comment by vancexu** [comment]
FYI we just released Cadence Web v3.6.0

**Comment by seriousben** [comment]
@vancexu I haven't tried with the CLI unfortunately. Do know if the server will be released soon?

**Comment by vancexu** [comment]
> @vancexu I haven't tried with the CLI unfortunately. Do know if the server will be released soon?

Sorry about postponing 0.11 release. We saw some degradation on activity timeout task and were working on it. Team needs more time to root cause and fix it. Is downgrade client an option asdf

**Comment by seriousben** [comment]
@vancexu Thanks a lot for the update.
