### ISSUE TITLE
Error "unable to decode argument" if return nil in local activity

### ISSUE THREAD

**Issue by meiliang86** [uber-go/cadence-client#943]
Not possible to make LocalActivity that returns nil in result. Workflow fails with

```
  "reason": "cadenceInternal:Generic",
  "details": "unable to decode argument: 0, **struct {}, with json error: EOF",
```

I've made a sample to demonstrate this problem:
https://github.com/olegmedvedev/cadence-local-activity-sample

**Comment by zhaytee** [comment]
Hi, we just encountered this issue. We use local activities for fetching db objects, and those activities return nil if the object is not found (i.e. we don't consider that to be an error). So as you can imagine, this is a fairly severe issue for our Cadence workflows.

Using a custom DataConverter reveals that the ToData() func is never called in this case, only FromData(), which results in FromData() trying to decode zero data. Hence the EOF error.

Any timeline on a fix? Currently using Go client 0.12.2

Thank you!
