### ISSUE TITLE
WorkflowRun.Get(ctx, &result) returns error on a newly started workflow

### ISSUE THREAD

**Issue by Shaddoll** [uber-go/cadence-client#947]
When I call ExecuteWorkflow and use WorkflowRun to get the result of the workflow, WorkflowRun.Get(ctx, &result)  can return a BadRequestError{Message: Requested workflow history not found, may have passed retention period.} sometimes.
A retry solve the problem, but it should be handled by the library.

**Comment by meiliang86** [comment]
@Shaddoll Do you have a multi-DC setup and did you do it from the passive DC?

**Comment by meiliang86** [comment]
@Shaddoll You should not get this error from active cluster. We added retry for this from passive side to get over replication lag. Closing this issue.
