### ISSUE TITLE
Reset workflows contains child workflow cause non-deterministic error

### ISSUE THREAD

**Issue by yux0** [uber-go/cadence-client#987]
**Describe the bug**
Reset workflows contains child workflow cause non-deterministic error if the child workflow id is not set.

https://github.com/uber-go/cadence-client/blob/5cc879bc3a9b2258ca569b5cb971231d9de0ff9b/internal/internal_event_handlers.go#L357
**To Reproduce**
Is the issue reproducible? 
- Yes

**Steps to reproduce the behavior:**
1. Implement a parent workflow contains a child wf
2. Do not set the workflow id in the child wf execution context
3. Start the wf and wait for it to finish
4. Reset the finished wf

**Expected behavior**
The workflow should be able to reset if there is no pending child wf.

**Screenshots**

**Additional context**
From this line: https://github.com/uber-go/cadence-client/blob/5cc879bc3a9b2258ca569b5cb971231d9de0ff9b/internal/internal_event_handlers.go#L357.
The default child wf is the run id + sequence id. However, after the wf is reset, the run id will be updated and caused the non-deterministic error

**Comment by yux0** [comment]
Directly change this could be a non-backward compatible change. One thing we can think of is to add a side effect for this generated child workflow id

**Comment by vancexu** [comment]
My understanding is: reset doesn't support workflow with child at all. 
It is kind of next steps for rest

**Comment by yux0** [comment]
It doesn't support if there is pending child workflows. With finished child workflows, I think it should support
